import { Download, ExternalLink, FileArchive, Info, Link2, Plus, Trash2, Unlink, UploadCloud } from "lucide-react"
import { useMemo, useState } from "react"
import { toast } from "sonner"
import { ConfirmDialog } from "@/components/shared/ConfirmDialog"
import { EmptyState } from "@/components/shared/EmptyState"
import { ErrorState } from "@/components/shared/ErrorState"
import { LoadingState } from "@/components/shared/LoadingState"
import { PaginationControls } from "@/components/shared/PaginationControls"
import { StatusBadge } from "@/components/shared/StatusBadge"
import { SurfaceCard } from "@/components/shared/SurfaceCard"
import { getApiErrorMessage } from "@/lib/apiResponse"
import { formatJalaliDateTime } from "@/lib/date/jalali"
import { useDebouncedValue } from "@/lib/useDebouncedValue"
import { useAuthStore } from "@/store/authStore"
import { Button } from "@workspace/ui/components/button"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@workspace/ui/components/dialog"
import { Input } from "@workspace/ui/components/input"
import { Label } from "@workspace/ui/components/label"
import { downloadArtifact } from "../api/artifacts.api"
import { useArtifacts, useCreateExternalArtifact, useDeleteArtifact, useUnlinkArtifact, useUploadArtifact } from "../hooks/useArtifacts"
import type { Artifact, ArtifactEntityType, ArtifactProvider, ArtifactRelationType, ArtifactType } from "../types/artifact.types"

const providerLabels: Record<ArtifactProvider, string> = { LOCAL: "فایل محلی", OBJECT_STORAGE: "فضای ابری", GOOGLE_DRIVE: "Google Drive", SHAREPOINT: "SharePoint", ONEDRIVE: "OneDrive", GITHUB: "GitHub", GENERIC_URL: "لینک خارجی" }
const relationLabels: Record<ArtifactRelationType, string> = { ATTACHMENT: "پیوست", PROPOSAL: "پیشنهاد", CONTRACT: "قرارداد", TECHNICAL_DOCUMENT: "سند فنی", MEETING_MINUTES: "صورت‌جلسه", SCREENSHOT: "تصویر", EVIDENCE: "مدرک", REFERENCE: "مرجع", OTHER: "سایر" }

export function ArtifactPanel({ entityType, entityId, title = "فایل‌ها و لینک‌ها", readOnly = false }: { entityType: ArtifactEntityType; entityId: string; title?: string; readOnly?: boolean }) {
  const permissions = useAuthStore((state) => state.user?.permissions ?? [])
  const canView = permissions.includes("artifact:view") || permissions.includes("attachment:view")
  const canCreate = !readOnly && (permissions.includes("artifact:create") || permissions.includes("attachment:manage"))
  const canDelete = !readOnly && (permissions.includes("artifact:delete") || permissions.includes("attachment:manage"))
  const canLink = !readOnly && (permissions.includes("artifact:link") || permissions.includes("attachment:manage"))
  const [page, setPage] = useState(1); const [type, setType] = useState<ArtifactType>(); const [searchInput, setSearchInput] = useState(""); const [mode, setMode] = useState<"upload" | "external">(); const [detail, setDetail] = useState<Artifact>(); const [deleteTarget, setDeleteTarget] = useState<Artifact>()
  const search = useDebouncedValue(searchInput.trim(), 300)
  const query = useArtifacts({ entityType, entityId, page, limit: 10, type, search: search || undefined }, canView)
  const remove = useDeleteArtifact(entityType, entityId); const unlink = useUnlinkArtifact(entityType, entityId)
  async function open(item: Artifact) { try { if (item.type === "EXTERNAL_URL" && item.externalUrl) window.open(item.externalUrl, "_blank", "noopener,noreferrer"); else await downloadArtifact(item.id, item.originalFileName || item.name) } catch (error) { toast.error(getApiErrorMessage(error, "باز کردن فایل انجام نشد.")) } }
  async function confirmDelete() { if (!deleteTarget) return; try { await remove.mutateAsync(deleteTarget.id); setDeleteTarget(undefined); toast.success("آرتیفکت حذف شد.") } catch (error) { toast.error(getApiErrorMessage(error, "حذف انجام نشد.")) } }
  async function unlinkCurrent(item: Artifact) { const link = item.links.find((row) => row.entityType === entityType && row.entityId === entityId); if (!link) return; try { await unlink.mutateAsync({ id: item.id, linkId: link.id }); toast.success("ارتباط حذف شد؛ اصل آرتیفکت باقی ماند.") } catch (error) { toast.error(getApiErrorMessage(error, "حذف ارتباط انجام نشد.")) } }
  return <SurfaceCard className="min-w-0 overflow-hidden">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--app-divider)] p-4 sm:px-5"><div><h2 className="text-sm font-bold">{title}</h2><p className="mt-1 text-xs text-[var(--app-text-secondary)]">فایل‌های بارگذاری‌شده و مراجع خارجی مرتبط</p></div>{canCreate ? <div className="flex gap-2"><Button size="sm" variant="outline" className="rounded-xl" onClick={() => setMode("external")}><Link2 className="size-4" />افزودن لینک</Button><Button size="sm" className="rounded-xl" onClick={() => setMode("upload")}><UploadCloud className="size-4" />بارگذاری فایل</Button></div> : null}</div>
    <div className="flex flex-wrap items-center gap-1 border-b p-3"><Input aria-label="جستجو در فایل‌ها و لینک‌ها" value={searchInput} onChange={(event) => { setSearchInput(event.target.value); setPage(1) }} className="ms-auto h-9 min-w-48 flex-1 sm:max-w-72" placeholder="جستجو در نام و توضیحات..." />{([{ label: "همه", value: undefined }, { label: "فایل‌ها", value: "FILE" }, { label: "لینک‌ها", value: "EXTERNAL_URL" }] as const).map((item) => <Button key={item.label} size="sm" variant={type === item.value ? "default" : "ghost"} className="rounded-lg" onClick={() => { setType(item.value); setPage(1) }}>{item.label}</Button>)}</div>
    <div className="min-h-44 p-4">{!canView ? <ErrorState title="دسترسی ندارید" description="مجوز مشاهده فایل‌ها و لینک‌ها برای شما فعال نیست." /> : query.isLoading ? <LoadingState rows={2} /> : query.isError ? <ErrorState title="خطا در دریافت آرتیفکت‌ها" description="دوباره تلاش کنید." onRetry={() => void query.refetch()} /> : query.data?.data.length ? <div className="grid gap-2 md:grid-cols-2">{query.data.data.map((item) => <article key={item.id} className="flex min-w-0 gap-3 rounded-2xl border p-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-[var(--app-primary-soft)] text-[var(--app-primary)]">{item.type === "FILE" ? <FileArchive className="size-5" /> : <ExternalLink className="size-5" />}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-xs font-bold">{item.name}</h3><StatusBadge tone="neutral" dot={false}>{providerLabels[item.provider]}</StatusBadge></div><p className="mt-1 text-xs text-[var(--app-text-secondary)]">{item.sizeBytes != null ? `${formatBytes(item.sizeBytes)} · ` : ""}{formatJalaliDateTime(item.createdAt)}</p>{item.description ? <p className="mt-2 line-clamp-2 text-xs text-[var(--app-text-secondary)]">{item.description}</p> : null}<div className="mt-3 flex flex-wrap gap-1"><Button size="sm" variant="outline" className="h-8 rounded-lg" onClick={() => void open(item)}>{item.type === "FILE" ? <Download className="size-3.5" /> : <ExternalLink className="size-3.5" />}باز کردن</Button><Button size="icon" variant="ghost" className="size-8" aria-label="جزئیات آرتیفکت" onClick={() => setDetail(item)}><Info className="size-3.5" /></Button>{canLink ? <Button size="icon" variant="ghost" className="size-8" aria-label="حذف ارتباط" onClick={() => void unlinkCurrent(item)}><Unlink className="size-3.5" /></Button> : null}{canDelete ? <Button size="icon" variant="ghost" className="size-8 text-[var(--destructive)]" aria-label="حذف آرتیفکت" onClick={() => setDeleteTarget(item)}><Trash2 className="size-3.5" /></Button> : null}</div></div></article>)}</div> : <EmptyState icon={FileArchive} title="هنوز فایل یا لینکی ثبت نشده است" description="یک فایل بارگذاری کنید یا مرجع خارجی اضافه کنید." action={canCreate ? <Button size="sm" className="rounded-xl" onClick={() => setMode("upload")}><Plus className="size-4" />افزودن</Button> : undefined} />}
      {query.data && query.data.meta.totalPages > 1 ? <PaginationControls page={query.data.meta.page} pageCount={query.data.meta.totalPages} total={query.data.meta.total} pageSize={10} onPageChange={setPage} disabled={query.isFetching} /> : null}</div>
    <ArtifactCreateDialog mode={mode} entityType={entityType} entityId={entityId} onClose={() => setMode(undefined)} />
    <ArtifactDetails artifact={detail} onClose={() => setDetail(undefined)} />
    <ConfirmDialog open={Boolean(deleteTarget)} onOpenChange={(open) => { if (!open) setDeleteTarget(undefined) }} title="حذف آرتیفکت" description="آرتیفکت و دسترسی به آن حذف می‌شود. حذف یک ارتباط به‌تنهایی، اصل آرتیفکت را حذف نمی‌کند." confirmLabel="حذف" tone="danger" isPending={remove.isPending} onConfirm={confirmDelete} />
  </SurfaceCard>
}

function ArtifactCreateDialog({ mode, entityType, entityId, onClose }: { mode?: "upload" | "external"; entityType: ArtifactEntityType; entityId: string; onClose: () => void }) {
  const upload = useUploadArtifact(entityType, entityId); const external = useCreateExternalArtifact(entityType, entityId)
  const [file, setFile] = useState<File>(); const [name, setName] = useState(""); const [url, setUrl] = useState(""); const [description, setDescription] = useState(""); const [provider, setProvider] = useState<ArtifactProvider | "AUTO">("AUTO"); const [relationType, setRelationType] = useState<ArtifactRelationType>("ATTACHMENT"); const [progress, setProgress] = useState(0)
  const detected = useMemo(() => detectProvider(url), [url]); if (!mode) return null
  const pending = upload.isPending || external.isPending
  async function submit() { try { if (mode === "upload") { if (!file) return; await upload.mutateAsync({ entityType, entityId, file, name: name || undefined, description: description || undefined, relationType, onProgress: setProgress }) } else { if (!name.trim() || !url.trim()) return; const selectedProvider = provider === "AUTO" ? detected : provider; await external.mutateAsync({ entityType, entityId, name: name.trim(), externalUrl: url.trim(), provider: selectedProvider, description: description.trim() || undefined, relationType, metadata: inferProviderMetadata(url.trim(), selectedProvider) }) } toast.success(mode === "upload" ? "فایل بارگذاری شد." : "لینک ثبت شد."); onClose() } catch (error) { toast.error(getApiErrorMessage(error, "ثبت آرتیفکت انجام نشد.")) } }
  return <Dialog open onOpenChange={(open) => { if (!open && !pending) onClose() }}><DialogContent dir="rtl" className="sm:max-w-lg"><DialogHeader><DialogTitle>{mode === "upload" ? "بارگذاری فایل" : "افزودن لینک آرتیفکت"}</DialogTitle><DialogDescription>{mode === "upload" ? "فایل به موجودیت جاری متصل و SHA-256 در سرور محاسبه می‌شود." : "مرجع خارجی ذخیره می‌شود و محتوای URL از سرور دریافت نخواهد شد."}</DialogDescription></DialogHeader><div className="grid gap-4">
    {mode === "upload" ? <><div role="button" tabIndex={0} className="rounded-2xl border border-dashed p-6 text-center" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); setFile(event.dataTransfer.files[0]) }}><UploadCloud className="mx-auto size-7 text-[var(--app-primary)]" /><Label htmlFor="artifact-file" className="mt-3 block cursor-pointer">{file?.name || "فایل را رها یا انتخاب کنید"}</Label><Input id="artifact-file" type="file" className="mt-3" onChange={(event) => setFile(event.target.files?.[0])} /></div>{progress ? <div className="h-2 overflow-hidden rounded-full bg-[var(--app-background)]"><div className="h-full bg-[var(--app-primary)]" style={{ width: `${progress}%` }} /></div> : null}</> : <><Field label="نام"><Input aria-label="نام" value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="URL"><Input aria-label="URL" dir="ltr" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://..." /></Field><Field label="سرویس"><select aria-label="سرویس" className={selectClass} value={provider} onChange={(event) => setProvider(event.target.value as ArtifactProvider | "AUTO")}><option value="AUTO">تشخیص خودکار ({providerLabels[detected]})</option>{(["GOOGLE_DRIVE", "SHAREPOINT", "ONEDRIVE", "GITHUB", "GENERIC_URL"] as ArtifactProvider[]).map((value) => <option key={value} value={value}>{providerLabels[value]}</option>)}</select></Field></>}
    {mode === "upload" ? <Field label="نام نمایشی (اختیاری)"><Input aria-label="نام نمایشی" value={name} onChange={(event) => setName(event.target.value)} /></Field> : null}<Field label="نوع ارتباط"><select aria-label="نوع ارتباط" className={selectClass} value={relationType} onChange={(event) => setRelationType(event.target.value as ArtifactRelationType)}>{Object.entries(relationLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="توضیحات"><textarea aria-label="توضیحات" className={textareaClass} rows={3} value={description} onChange={(event) => setDescription(event.target.value)} /></Field>
  </div><div className="flex justify-end gap-2"><Button variant="outline" className="rounded-xl" disabled={pending} onClick={onClose}>انصراف</Button><Button className="rounded-xl" disabled={pending || (mode === "upload" ? !file : !name.trim() || !url.trim())} onClick={() => void submit()}>{pending ? "در حال ثبت..." : "ثبت"}</Button></div></DialogContent></Dialog>
}

function ArtifactDetails({ artifact, onClose }: { artifact?: Artifact; onClose: () => void }) { if (!artifact) return null; return <Dialog open onOpenChange={(open) => { if (!open) onClose() }}><DialogContent dir="rtl" className="sm:max-w-xl"><DialogHeader><DialogTitle>{artifact.name}</DialogTitle><DialogDescription>{providerLabels[artifact.provider]}</DialogDescription></DialogHeader><dl className="grid gap-3 text-xs sm:grid-cols-2"><Meta label="نوع" value={artifact.type === "FILE" ? "فایل" : "لینک خارجی"} /><Meta label="MIME" value={artifact.mimeType} /><Meta label="حجم" value={artifact.sizeBytes == null ? undefined : formatBytes(artifact.sizeBytes)} /><Meta label="ایجادکننده" value={artifact.uploadedBy?.fullName || artifact.uploadedBy?.email} /><Meta label="تاریخ ایجاد" value={formatJalaliDateTime(artifact.createdAt)} /><Meta label="SHA-256" value={artifact.sha256} wide /><Meta label="توضیحات" value={artifact.description} wide /></dl><div><h3 className="mb-2 text-xs font-bold">ارتباط‌ها</h3><div className="grid gap-2">{artifact.links.map((link) => <div key={link.id} className="rounded-xl bg-[var(--app-background)] p-3 text-xs">{link.entityType} · {link.entityId} · {relationLabels[link.relationType]}</div>)}</div></div></DialogContent></Dialog> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid gap-2"><Label>{label}</Label>{children}</div> }
function Meta({ label, value, wide }: { label: string; value?: string | null; wide?: boolean }) { return <div className={`rounded-xl bg-[var(--app-background)] p-3 ${wide ? "sm:col-span-2" : ""}`}><dt className="text-[var(--app-text-secondary)]">{label}</dt><dd className="mt-1 break-all font-bold">{value || "—"}</dd></div> }
function detectProvider(value: string): ArtifactProvider { try { const host = new URL(value).hostname.toLowerCase(); if (host.includes("drive.google.com") || host.includes("docs.google.com")) return "GOOGLE_DRIVE"; if (host.includes("sharepoint.com")) return "SHAREPOINT"; if (host.includes("1drv.ms") || host.includes("onedrive.live.com")) return "ONEDRIVE"; if (host === "github.com" || host.endsWith(".github.com")) return "GITHUB" } catch { /* incomplete input */ } return "GENERIC_URL" }
function inferProviderMetadata(value: string, provider: ArtifactProvider): Record<string, string> | undefined { try { const url = new URL(value); const parts = url.pathname.split("/").filter(Boolean); if (provider === "GOOGLE_DRIVE") { const fileId = url.searchParams.get("id") || (parts[0] === "file" && parts[1] === "d" ? parts[2] : undefined) || (parts[0] === "document" && parts[1] === "d" ? parts[2] : undefined); return fileId ? { fileId } : undefined } if (provider === "GITHUB" && parts.length >= 2) { const metadata: Record<string, string> = { repository: `${parts[0]}/${parts[1]}` }; if ((parts[2] === "blob" || parts[2] === "tree") && parts[3]) { metadata.ref = parts[3]; if (parts.length > 4) metadata.path = parts.slice(4).join("/") } return metadata } } catch { /* backend validates the URL */ } return undefined }
function formatBytes(value: number) { if (value < 1024) return `${value.toLocaleString("fa-IR")} بایت`; if (value < 1024 ** 2) return `${(value / 1024).toLocaleString("fa-IR", { maximumFractionDigits: 1 })} KB`; return `${(value / 1024 ** 2).toLocaleString("fa-IR", { maximumFractionDigits: 1 })} MB` }
const selectClass = "h-11 w-full rounded-xl border border-input bg-transparent px-3 text-sm"
const textareaClass = "w-full rounded-xl border border-input bg-transparent p-3 text-sm"
