import { CheckCircle2, ClipboardCheck, FileArchive, RotateCcw, Send, XCircle } from "lucide-react"
import { useMemo, useState } from "react"
import { toast } from "sonner"
import { StatusBadge } from "@/components/shared/StatusBadge"
import { SurfaceCard } from "@/components/shared/SurfaceCard"
import { LoadingState } from "@/components/shared/LoadingState"
import { ErrorState } from "@/components/shared/ErrorState"
import { useArtifacts } from "@/features/artifacts/hooks/useArtifacts"
import { getApiErrorMessage } from "@/lib/apiResponse"
import { formatJalaliDateTime } from "@/lib/date/jalali"
import { useDebouncedValue } from "@/lib/useDebouncedValue"
import { useAuthStore } from "@/store/authStore"
import { Button } from "@workspace/ui/components/button"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@workspace/ui/components/dialog"
import { Input } from "@workspace/ui/components/input"
import { Label } from "@workspace/ui/components/label"
import { TaskOptionSelect } from "./TaskOptionSelect"
import { useDecideTaskReview, useSubmitTaskReview, useTaskAssignees, useTaskReviews } from "../hooks/useTasks"
import type { Task, TaskOption, TaskReviewDecision, TaskReviewStatus } from "../types/task.types"

const statusLabel: Record<TaskReviewStatus, string> = { NOT_REQUIRED: "بدون نیاز به بازبینی", DRAFT: "پیش‌نویس", PENDING_REVIEW: "در انتظار بازبینی", CHANGES_REQUESTED: "نیازمند اصلاح", APPROVED: "تأییدشده" }
const decisionLabel: Record<TaskReviewDecision, string> = { PENDING: "در انتظار تصمیم", APPROVED: "تأییدشده", CHANGES_REQUESTED: "اصلاحات درخواست‌شده", CANCELLED: "لغوشده" }

export function TaskReviewSection({ task }: { task: Task }) {
  const user = useAuthStore((state) => state.user)
  const permissions = user?.permissions ?? []
  const canSubmit = permissions.includes("task:submit-review") && task.requiresReview && !["DONE", "CANCELLED"].includes(task.status) && ["DRAFT", "CHANGES_REQUESTED"].includes(task.reviewStatus)
  const canReview = permissions.includes("task:review") && task.reviewStatus === "PENDING_REVIEW" && task.reviewerId === user?.id
  const reviews = useTaskReviews(task.id, permissions.includes("task:view") || permissions.includes("task:review"))
  const [dialog, setDialog] = useState<"submit" | "approve" | "changes">()
  const latest = reviews.data?.[0] ?? task.reviewRounds?.[0]
  return <SurfaceCard id="review" className="min-w-0 overflow-hidden">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--app-divider)] px-4 py-3 sm:px-5"><div className="flex items-center gap-2"><ClipboardCheck className="size-4 text-[var(--app-primary)]" /><h2 className="text-sm font-bold">بازبینی کار</h2><StatusBadge tone={reviewTone(task.reviewStatus)}>{statusLabel[task.reviewStatus]}</StatusBadge></div><div className="flex flex-wrap gap-2">{canSubmit ? <Button size="sm" className="rounded-xl" onClick={() => setDialog("submit")}>{task.reviewStatus === "CHANGES_REQUESTED" ? <RotateCcw className="size-4" /> : <Send className="size-4" />}{task.reviewStatus === "CHANGES_REQUESTED" ? "ارسال مجدد" : "ارسال برای بازبینی"}</Button> : null}{canReview ? <><Button size="sm" className="rounded-xl" onClick={() => setDialog("approve")}><CheckCircle2 className="size-4" />تأیید</Button><Button size="sm" variant="outline" className="rounded-xl text-[var(--destructive)]" onClick={() => setDialog("changes")}><XCircle className="size-4" />درخواست اصلاح</Button></> : null}</div></div>
    <div className="grid gap-4 p-4 sm:p-5">
      <div className="grid gap-3 sm:grid-cols-3"><Info label="بازبین" value={task.reviewer?.fullName || task.reviewer?.email || "—"} /><Info label="تعداد دوره‌ها" value={(task._count?.reviewRounds ?? reviews.data?.length ?? 0).toLocaleString("fa-IR")} /><Info label="آخرین دوره" value={latest ? `دوره ${latest.roundNumber.toLocaleString("fa-IR")}` : "—"} /></div>
      {task.reviewStatus === "CHANGES_REQUESTED" && latest?.reviewComment ? <div className="rounded-2xl border border-[var(--destructive)]/20 bg-[var(--destructive-soft)] p-4"><p className="text-xs font-bold text-[var(--destructive)]">بازخورد بازبین</p><p className="mt-2 whitespace-pre-wrap text-sm">{latest.reviewComment}</p></div> : null}
      {reviews.isLoading ? <LoadingState rows={2} /> : reviews.isError ? <ErrorState title="خطا در دریافت تاریخچه بازبینی" description="دوباره تلاش کنید." onRetry={() => void reviews.refetch()} /> : reviews.data?.length ? <div className="grid gap-3">{reviews.data.map((round) => <article key={round.id} className="rounded-2xl border border-[var(--app-divider)] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-bold">دوره {round.roundNumber.toLocaleString("fa-IR")}</p><StatusBadge tone={decisionTone(round.decision)}>{decisionLabel[round.decision]}</StatusBadge></div><div className="mt-3 grid gap-2 text-xs text-[var(--app-text-secondary)] sm:grid-cols-2"><p>ارسال‌کننده: {round.submittedBy?.fullName || round.submittedBy?.email}</p><p>بازبین: {round.reviewer?.fullName || round.reviewer?.email}</p><p>ارسال: {formatJalaliDateTime(round.submittedAt)}</p>{round.reviewedAt ? <p>تصمیم: {formatJalaliDateTime(round.reviewedAt)}</p> : null}</div>{round.submissionNote ? <p className="mt-3 whitespace-pre-wrap text-xs">یادداشت ارسال: {round.submissionNote}</p> : null}{round.reviewComment ? <p className="mt-2 whitespace-pre-wrap text-xs font-bold">نظر بازبین: {round.reviewComment}</p> : null}{round.artifacts?.length ? <div className="mt-3 flex flex-wrap gap-2">{round.artifacts.map(({ artifact }) => <span key={artifact.id} className="inline-flex items-center gap-1 rounded-lg bg-[var(--app-background)] px-2 py-1 text-xs"><FileArchive className="size-3.5" />{artifact.name}</span>)}</div> : null}</article>)}</div> : <p className="text-xs text-[var(--app-text-secondary)]">هنوز دوره‌ای برای بازبینی ثبت نشده است.</p>}
    </div>
    <SubmitReviewDialog open={dialog === "submit"} task={task} nextRound={(task._count?.reviewRounds ?? reviews.data?.length ?? 0) + 1} onClose={() => setDialog(undefined)} />
    <DecisionDialog mode={dialog === "approve" ? "approve" : dialog === "changes" ? "request-changes" : undefined} task={task} onClose={() => setDialog(undefined)} />
  </SurfaceCard>
}

function SubmitReviewDialog({ open, task, nextRound, onClose }: { open: boolean; task: Task; nextRound: number; onClose: () => void }) {
  const permissions = useAuthStore((state) => state.user?.permissions ?? [])
  const canAssignReviewer = permissions.includes("task:assign-reviewer")
  const [search, setSearch] = useState(""); const debounced = useDebouncedValue(search, 250)
  const reviewers = useTaskAssignees(debounced, open && canAssignReviewer)
  const options = useMemo(() => reviewers.data?.pages.flatMap((page) => page.data).filter((item) => item.id !== task.assignedToId).map((item) => ({ id: item.id, label: item.fullName || item.email || item.id, secondary: item.email || undefined })) ?? [], [reviewers.data, task.assignedToId])
  const [reviewer, setReviewer] = useState<TaskOption | undefined>(task.reviewer ? { id: task.reviewer.id, label: task.reviewer.fullName || task.reviewer.email || task.reviewer.id } : undefined)
  const [note, setNote] = useState(""); const [selected, setSelected] = useState<string[]>([])
  const artifacts = useArtifacts({ entityType: "TASK", entityId: task.id, page: 1, limit: 100 }, open)
  const submit = useSubmitTaskReview()
  async function save() { if (!reviewer) return toast.error("بازبین را انتخاب کنید."); try { await submit.mutateAsync({ id: task.id, payload: { reviewerId: reviewer.id, note: note.trim() || undefined, artifactIds: selected } }); toast.success("کار برای بازبینی ارسال شد."); onClose() } catch (error) { toast.error(getApiErrorMessage(error, "ارسال برای بازبینی انجام نشد.")) } }
  return <Dialog open={open} onOpenChange={(value) => { if (!value && !submit.isPending) onClose() }}><DialogContent dir="rtl" className="sm:max-w-xl"><DialogHeader><DialogTitle>{task.reviewStatus === "CHANGES_REQUESTED" ? "ارسال مجدد برای بازبینی" : "ارسال برای بازبینی"}</DialogTitle><DialogDescription>دوره {nextRound.toLocaleString("fa-IR")} ایجاد می‌شود و سوابق دوره‌های قبلی حفظ خواهند شد.</DialogDescription></DialogHeader><div className="grid gap-4"><div className="grid gap-2"><Label>بازبین</Label>{canAssignReviewer ? <TaskOptionSelect value={reviewer?.id} selectedOption={reviewer} options={options} onChange={setReviewer} search={search} onSearchChange={setSearch} placeholder="انتخاب بازبین" loading={reviewers.isLoading} hasMore={reviewers.hasNextPage} loadingMore={reviewers.isFetchingNextPage} onLoadMore={() => void reviewers.fetchNextPage()} /> : <Input value={reviewer?.label || "بازبین تعیین نشده"} disabled />}</div><div className="grid gap-2"><Label htmlFor="review-note">یادداشت ارسال</Label><textarea id="review-note" className="min-h-24 rounded-xl border bg-transparent p-3 text-sm" value={note} onChange={(event) => setNote(event.target.value)} /></div><div className="grid gap-2"><Label>مستندات ارسالی (اختیاری)</Label>{artifacts.data?.data.length ? <div className="grid max-h-44 gap-2 overflow-y-auto rounded-xl border p-2">{artifacts.data.data.map((artifact) => <label key={artifact.id} className="flex cursor-pointer items-center gap-2 rounded-lg p-2 hover:bg-[var(--app-background)]"><input type="checkbox" checked={selected.includes(artifact.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, artifact.id] : current.filter((id) => id !== artifact.id))} /><span className="text-xs">{artifact.name}</span></label>)}</div> : <p className="text-xs text-[var(--app-text-secondary)]">از پنل فایل‌ها، مستندات را به این کار متصل کنید.</p>}</div></div><div className="flex justify-end gap-2"><Button variant="outline" disabled={submit.isPending} onClick={onClose}>انصراف</Button><Button disabled={submit.isPending || !reviewer} onClick={() => void save()}>ارسال</Button></div></DialogContent></Dialog>
}

function DecisionDialog({ mode, task, onClose }: { mode?: "approve" | "request-changes"; task: Task; onClose: () => void }) { const [comment, setComment] = useState(""); const decide = useDecideTaskReview(); if (!mode) return null; const required = mode === "request-changes"; async function save() { if (required && !comment.trim()) return toast.error("توضیح اصلاحات الزامی است."); try { await decide.mutateAsync({ id: task.id, decision: mode!, comment }); toast.success(required ? "اصلاحات درخواست شد." : "کار تأیید شد."); onClose() } catch (error) { toast.error(getApiErrorMessage(error, "ثبت تصمیم انجام نشد.")) } } return <Dialog open onOpenChange={(value) => { if (!value && !decide.isPending) onClose() }}><DialogContent dir="rtl" className="sm:max-w-lg"><DialogHeader><DialogTitle>{required ? "درخواست اصلاح" : "تأیید کار"}</DialogTitle><DialogDescription>{required ? "بازخورد لازم برای انجام اصلاحات را ثبت کنید." : "آیا این ارسال را تأیید می‌کنید؟"}</DialogDescription></DialogHeader><div className="grid gap-2"><Label htmlFor="review-comment">نظر بازبین {required ? "*" : "(اختیاری)"}</Label><textarea id="review-comment" className="min-h-28 rounded-xl border bg-transparent p-3 text-sm" value={comment} onChange={(event) => setComment(event.target.value)} /></div><div className="flex justify-end gap-2"><Button variant="outline" disabled={decide.isPending} onClick={onClose}>انصراف</Button><Button disabled={decide.isPending || (required && !comment.trim())} onClick={() => void save()}>{required ? "ثبت درخواست اصلاح" : "تأیید"}</Button></div></DialogContent></Dialog> }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-[var(--app-background)] p-3"><p className="text-xs text-[var(--app-text-secondary)]">{label}</p><p className="mt-1 text-xs font-bold">{value}</p></div> }
function reviewTone(status: TaskReviewStatus): "neutral" | "primary" | "success" | "error" | "warning" { return status === "APPROVED" ? "success" : status === "CHANGES_REQUESTED" ? "error" : status === "PENDING_REVIEW" ? "warning" : status === "DRAFT" ? "primary" : "neutral" }
function decisionTone(decision: TaskReviewDecision): "neutral" | "success" | "error" | "warning" { return decision === "APPROVED" ? "success" : decision === "CHANGES_REQUESTED" ? "error" : decision === "PENDING" ? "warning" : "neutral" }
