export type NotificationChannel = "EMAIL" | "SMS" | "PUSH" | "IN_APP"

export type NotificationEventName =
  | "MEETING.CREATED"
  | "MEETING.UPDATED"
  | "MEETING.CANCELLED"
  | "MEETING.REMINDER"
  | "TASK.ASSIGNED"
  | "TASK.REASSIGNED"
  | "TASK.COMPLETED"
  | "TASK.DUE_SOON"
  | "TASK.OVERDUE"
  | "OPPORTUNITY.STAGE_CHANGED"
  | "CONVERSATION.MESSAGE_CREATED"
  | "CONVERSATION.QUESTION_CREATED"
  | "CONVERSATION.REPLY_CREATED"
  | "CONVERSATION.RESOLVED"

export type NotificationDeliveryStatus =
  | "PENDING"
  | "PROCESSING"
  | "SENT"
  | "DELIVERED"
  | "FAILED"
  | "RETRYING"
  | "SKIPPED"

export type NotificationRecipientType =
  | "USER"
  | "ROLE"
  | "TEAM"
  | "ASSIGNEE"
  | "OWNER"
  | "CREATOR"
  | "MANAGER"
