export const uiText = {
  app: {
    invalidResponse: "پاسخ دریافتی قابل نمایش نیست. لطفاً دوباره تلاش کنید.",
    loading: "در حال آماده‌سازی...",
    sessionUnavailable: "بررسی نشست ممکن نیست. اتصال را بررسی کنید و دوباره تلاش کنید.",
    login: "رفتن به صفحه ورود",
    unauthorized: "نشست شما معتبر نیست؛ دوباره وارد شوید.",
    forbidden: "دسترسی به این بخش برای شما مجاز نیست.",
    notFound: "صفحه یا اطلاعات موردنظر پیدا نشد.",
    conflict: "این عملیات با وضعیت فعلی اطلاعات سازگار نیست.",
    validation: "اطلاعات واردشده را بررسی و اصلاح کنید.",
    server: "سرویس موقتاً در دسترس نیست. دوباره تلاش کنید.",
    network: "ارتباط با سرور برقرار نشد. اتصال خود را بررسی کنید.",
    unexpected: "انجام عملیات با خطا مواجه شد.",
    forbiddenTitle: "دسترسی غیرمجاز",
    notFoundTitle: "صفحه پیدا نشد",
    logoutFailed: "خروج محلی انجام شد، اما پایان نشست روی سرور تأیید نشد. اتصال را بررسی کنید.",
    name: "NESHANE CRM",
    tagline: "فضای کاری امن و یکپارچه",
    workspaceSubtitle: "فضای کاری مدیریت ارتباط با مشتری",
  },

  common: {
    save: "ذخیره",
    loading: "در حال دریافت اطلاعات...",
    refresh: "به‌روزرسانی",
    active: "فعال",
    inactive: "غیرفعال",
    forms: { required: "تکمیل این فیلد الزامی است.", invalidEmail: "ایمیل معتبر نیست.", shortPassword: "رمز عبور باید حداقل ۶ کاراکتر باشد." },
    home: "خانه",
    profile: "پروفایل",
    logout: "خروج",
    loggingOut: "در حال خروج...",
    logoutFromAccount: "خروج از حساب",
    notifications: "اعلان‌ها",
    accountSecurity: "امنیت حساب",
    openCloseMainMenu: "باز و بسته کردن منوی اصلی",
    underDevelopment: "در حال توسعه",
    notAvailable: "-",
    fallbackUserInitial: "U",
    retry: "تلاش دوباره",
    confirm: "تأیید",
    cancel: "انصراف",
    processing: "در حال انجام...",
    listSeparator: "، ",
    table: {
      loadError: "دریافت اطلاعات با خطا مواجه شد.",
      noResults: "اطلاعاتی پیدا نشد",
      noResultsDescription: "فیلترهای جستجو را تغییر دهید.",
      caption: "فهرست اطلاعات",
      searchPlaceholder: "جستجو...",
      clearFilters: "پاک کردن فیلترها",
    },
    pagination: {
      rows: "ردیف",
      rowsPerPage: "تعداد ردیف در هر صفحه",
      page: "صفحه",
      of: "از",
      previous: "قبلی",
      next: "بعدی",
    },
  },

  adminUsers: {
    title: "مدیریت کاربران",
    create: "افزودن کاربر",
    noTeam: "بدون تیم",
    fields: { fullName: "نام کامل", email: "ایمیل", password: "رمز عبور اولیه", roleChoice: "نقش", teamId: "تیم", status: "وضعیت" },
    roleLabels: { ADMIN: "ادمین", MANAGER: "مدیر فروش", REP: "کارشناس فروش", BOARDS: "برد / مشاهده‌گر" },
    search: "جستجو بر اساس نام یا ایمیل",
  },

  navigation: {
    groups: {
      sales: "عملیات فروش",
      technical: "مرکز فنی",
      management: "مدیریت",
      account: "حساب",
    },
    dashboard: "داشبورد",
    companies: "شرکت‌ها",
    opportunities: "فرصت‌ها",
    pipeline: "پایپ‌لاین",
    tasks: "کارها",
    meetings: "جلسات",
    followUps: "پیگیری‌ها",
    notifications: "اعلان‌ها",
    people: "افراد",
    activities: "فعالیت‌ها",
    reports: "گزارش‌ها",
    users: "کاربران",
    teams: "تیم‌ها",
    exchangeRates: "نرخ دلار",
    rolesAndPermissions: "نقش‌ها و مجوزها",
    libraries: "کتابخانه‌ها",
    pipelineSettings: "تنظیمات پایپ‌لاین",
    auditLogs: "رویدادهای ممیزی",
    accountSecurity: "امنیت حساب",
    usageAndQuota: "مصرف و سهمیه",
  },

  technicalCenter: {
    comingSoon: "این بخش در حال آماده‌سازی است.",
    releases: { title: "نسخه‌ها و انتشارها", description: "فضای نسخه‌ها و انتشارهای محصولات نرم‌افزاری" },
    knowledgeBase: { title: "پایگاه دانش", description: "مرجع دانش، راهنماها و تجربه‌های فنی تیم" },
    tenders: { title: "مناقصات", description: "فضای اطلاعات و پیگیری فنی مناقصات" },
    documents: { title: "مستندات فنی", description: "مرجع مستندات و راهنماهای فنی محصولات" },
    resources: { title: "منابع و فایل‌ها", description: "فضای منابع و فایل‌های موردنیاز تیم فنی" },
  },

  products: {
    type: "نوع محصول",
    chooseType: "نوع محصول را انتخاب کنید",
    allTypes: "همه محصولات",
    types: { HARDWARE: "سخت‌افزاری", SOFTWARE: "نرم‌افزاری" },
  },

  auth: {
    login: {
      title: "خوش آمدید",
      description: "برای ورود به سامانه، اطلاعات حساب کاربری خود را وارد کنید.",
      emailLabel: "ایمیل سازمانی",
      emailPlaceholder: "your_mail@rsa.ir",
      passwordLabel: "رمز عبور",
      passwordPlaceholder: "••••••••",
      forgotPassword: "رمز عبور را فراموش کرده‌اید؟",
      submit: "ورود به سامانه",
      submitting: "در حال ورود...",
      passkeyNotice:
        "ورود با Passkey و حساب سازمانی در مرحله بعدی فعال خواهد شد.",
      accessNotice: "دسترسی به سامانه مطابق سطح مجوز سازمانی شما کنترل می‌شود.",
      passwordVisibility: {
        show: "نمایش رمز عبور",
        hide: "مخفی کردن رمز عبور",
      },
      validation: {
        invalidEmail: "ایمیل واردشده معتبر نیست",
        shortPassword: "رمز عبور باید حداقل ۶ کاراکتر باشد",
      },
      errors: {
        loginFailed: "ورود به سامانه انجام نشد",
      },
      hero: {
        badge: "تجربه جدید مدیریت فروش سازمانی",
        headline: "مدیریت ارتباط با مشتری، یکپارچه و هوشمند",
        highlights: [
          "مدیریت متمرکز ارتباط با مشتری",
          "کنترل دسترسی مبتنی بر نقش و مجوز",
          "زیرساخت آماده برای ورود بدون گذرواژه",
        ],
      },
    },
  },

  dashboard: {
    hero: {
      badge: "نمای زنده عملکرد فروش",
      greeting: "سلام،",
      description:
        "تصویری یکپارچه از ارزش پایپ‌لاین، عملکرد فروش و نقاطی که امروز به توجه شما نیاز دارند.",
      limitedDescription:
        "فضای کاری شما آماده است. گزینه‌های در دسترس بر اساس مجوزهای سازمانی شما نمایش داده می‌شوند.",
      stats: {
        winRate: "نرخ موفقیت دوره",
        activeCount: "فرصت فعال",
      },
    },
    actions: {
      opportunities: "مشاهده فرصت‌ها",
      companies: "مشاهده شرکت‌ها",
      activities: "مشاهده فعالیت‌ها",
    },
    permissions: {
      title: "نمای مدیریتی برای این حساب فعال نیست",
      description:
        "برای مشاهده شاخص‌ها و نمودارهای تحلیلی داشبورد، مجوز گزارش‌گیری سازمانی موردنیاز است. سایر بخش‌های مجاز از منوی اصلی در دسترس هستند.",
    },
    units: {
      rial: "ریال",
      opportunity: "فرصت",
    },
    kpis: {
      totalPortfolio: { title: "ارزش کل سبد فرصت‌ها" },
      activePipeline: { title: "ارزش پایپ‌لاین فعال", subtitle: "فرصت فعال" },
      totalWon: { title: "فروش موفق تجمعی", subtitle: "فرصت موفق" },
      periodWon: { title: "فروش موفق دوره", subtitle: "فرصت موفق در دوره" },
    },
    trend: {
      title: "ریتم ۱۲ ماهه فرصت‌ها",
      modes: { count: "تعداد", value: "ارزش" },
      series: { created: "ایجادشده", won: "موفق", lost: "از دست‌رفته" },
      axis: {
        count: "تعداد فرصت",
        value: "ارزش",
        valueHint:
          "مقادیر محور عمودی در حالت ارزش به‌صورت خلاصه نمایش داده می‌شوند.",
      },
      activeSummary: {
        countPrefix: "تعداد فرصت‌های فعال تا",
        valuePrefix: "ارزش فرصت‌های فعال تا",
        monthSuffix: "ماه",
      },
      currentPeriodFallback: "ماه جاری",
      ariaLabel: "نمودار روند دوازده‌ماهه فرصت‌ها",
    },
    status: {
      title: "ترکیب سبد فرصت‌ها",
      description: "سهم فرصت‌های فعال، موفق و از دست‌رفته از کل سبد جاری",
      total: "کل فرصت‌ها",
      active: "فعال",
      won: "موفق",
      lost: "از دست‌رفته",
      ariaLabel: "نمودار ترکیب سبد فرصت‌ها",
      legend: { countLabel: "تعداد فرصت", shareLabel: "سهم از کل" },
    },
    attention: {
      title: "نیازمند توجه",
      description:
        "مواردی که از زمان‌بندی مورد انتظار عبور کرده‌اند یا نیاز به اقدام دارند",
      empty: "در حال حاضر مورد فوری قابل نمایشی وجود ندارد.",
      types: { opportunity: "فرصت", task: "کار", meeting: "جلسه" },
    },
    recentActivities: {
      title: "آخرین فعالیت‌ها",
      description: "جدیدترین تعاملات ثبت‌شده در محدوده دسترسی شما",
      viewAll: "مشاهده همه",
      empty: "هنوز فعالیتی برای نمایش وجود ندارد.",
      restrictedTitle: "فعالیت‌های اخیر در دسترس نیست",
      restrictedDescription:
        "این بخش فقط برای کاربران دارای مجوز مشاهده فعالیت‌ها نمایش داده می‌شود.",
    },
    errors: {
      summaryTitle: "دریافت اطلاعات داشبورد انجام نشد",
      summaryFallback:
        "در حال حاضر امکان دریافت اطلاعات تحلیلی داشبورد وجود ندارد.",
      activitiesFallback:
        "در حال حاضر امکان دریافت آخرین فعالیت‌ها وجود ندارد.",
      retry: "تلاش دوباره",
    },
    welcomeBadge: "فضای کاری مدیریت فروش",
    welcomeTitlePrefix: "خوش آمدید،",
    welcomeDescription:
      "داشبورد مدیریتی شما آماده است. اطلاعات، فرصت‌ها و فعالیت‌های مرتبط با سطح دسترسی شما از این فضا در دسترس خواهد بود.",
    nextStep: {
      title: "داشبورد تحلیلی",
      description:
        "در مرحله بعد، شاخص‌های فروش، وضعیت پایپ‌لاین، فرصت‌های فعال و فعالیت‌های کلیدی به این بخش اضافه می‌شوند.",
    },
  },

  companies: {
    list: {
      title: "شرکت‌ها",
      description:
        "نمای یکپارچه مشتریان سازمانی، مالکیت حساب‌ها و وضعیت ارتباطات فروش",
      create: "ایجاد شرکت",
      searchPlaceholder: "جستجو در نام، صنعت، شهر یا شماره تماس...",
      unassigned: "بدون مالک",
      archived: "بایگانی‌شده",
      active: "فعال",
      openCompany: "مشاهده جزئیات شرکت",
      columns: {
        company: "شرکت",
        industry: "صنعت",
        priority: "اولویت",
        owner: "مالک",
        status: "وضعیت",
        updatedAt: "آخرین بروزرسانی",
      },
      filters: {
        allPriorities: "همه اولویت‌ها",
        allOwners: "همه مالکیت‌ها",
        mine: "شرکت‌های من",
        team: "تیم من",
        unassigned: "بدون مالک",
        activeOnly: "فعال",
        archivedOnly: "بایگانی‌شده",
        allArchiveStates: "همه وضعیت‌ها",
      },
      priorities: {
        LOW: "کم",
        MEDIUM: "متوسط",
        HIGH: "زیاد",
        STRATEGIC: "استراتژیک",
      },
      emptyTitle: "شرکتی برای نمایش وجود ندارد",
      emptyDescription:
        "فیلترها را تغییر دهید یا در صورت داشتن مجوز، یک شرکت جدید ایجاد کنید.",
      errorTitle: "دریافت فهرست شرکت‌ها انجام نشد",
      errorDescription:
        "امکان دریافت اطلاعات شرکت‌ها از سرور وجود ندارد. دوباره تلاش کنید.",
    },

    detail: {
      back: "بازگشت به شرکت‌ها",
      edit: "ویرایش شرکت",
      active: "فعال",
      archived: "بایگانی‌شده",
      unassigned: "بدون مالک",
      notSpecified: "ثبت نشده",
      errorTitle: "دریافت اطلاعات شرکت انجام نشد",
      errorDescription:
        "اطلاعات این شرکت در حال حاضر قابل دریافت نیست. دوباره تلاش کنید.",
      metrics: {
        pipelineValue: "ارزش پایپ‌لاین فعال",
        pipelineHint: "جمع فرصت‌های غیرنهایی",
        openOpportunities: "فرصت فعال",
        people: "افراد مرتبط",
        lastInteraction: "آخرین تعامل",
      },
      sections: {
        overview: "تصویر کلی شرکت",
        overviewDescription:
          "اطلاعات کلیدی حساب برای تصمیم‌گیری سریع در یک نگاه",
        opportunities: "فرصت‌های فروش",
        opportunitiesDescription:
          "آخرین فرصت‌های مرتبط با این شرکت و وضعیت فعلی آن‌ها",
        legal: "اطلاعات ثبتی و سازمانی",
        people: "افراد کلیدی",
        peopleDescription: "مخاطبان و افراد ثبت‌شده در این حساب",
        timeline: "خط زمانی تعاملات",
        timelineDescription:
          "آخرین فعالیت‌های ثبت‌شده برای حفظ Context ارتباط با مشتری",
        ecosystem: "اکوسیستم حساب",
        ecosystemDescription: "دارایی‌ها و اطلاعات تکمیلی متصل به این شرکت",
      },
      fields: {
        legalName: "نام حقوقی",
        brandName: "نام تجاری",
        industry: "صنعت",
        owner: "مالک حساب",
        team: "تیم مالک",
        city: "شهر / استان",
        phone: "تلفن مرکزی",
        website: "وب‌سایت",
        source: "منبع ورود",
        registrationNumber: "شماره ثبت",
        nationalId: "شناسه ملی",
        economicCode: "کد اقتصادی",
        establishmentDate: "تاریخ تأسیس",
        activityStatus: "وضعیت فعالیت",
        employeeCount: "تعداد پرسنل",
        registeredCapital: "سرمایه ثبتی",
        createdAt: "تاریخ ایجاد",
        updatedAt: "آخرین بروزرسانی",
      },
      empty: {
        opportunitiesTitle: "فرصت فروشی ثبت نشده",
        opportunitiesDescription: "هنوز فرصت فروشی برای این شرکت ثبت نشده است.",
        peopleTitle: "فردی ثبت نشده",
        peopleDescription: "هنوز فرد یا مخاطبی برای این شرکت ثبت نشده است.",
      },
      timeline: {
        emptyTitle: "فعالیتی ثبت نشده",
        emptyDescription:
          "با ثبت تماس، جلسه یا تعامل بعدی، تاریخچه ارتباط اینجا شکل می‌گیرد.",
        fallbackTitle: "فعالیت شرکت",
      },
      ecosystem: {
        branches: "شعب",
        social: "کانال اجتماعی",
        legalDocuments: "اسناد حقوقی",
        callCard: "کال کارت",
      },
    },

    form: {
      createTitle: "ثبت شرکت جدید",
      createDescription:
        "اطلاعات پایه، بازار و مشخصات ثبتی شرکت را در یک فرم یکپارچه ثبت کنید.",
      editTitle: "ویرایش اطلاعات شرکت",
      editDescription:
        "اطلاعات حساب سازمانی را با حفظ ساختار فعلی و بدون خروج از صفحه بروزرسانی کنید.",
      createSubmit: "ثبت شرکت",
      editSubmit: "ذخیره تغییرات",
      close: "بستن فرم",
      sideBadge: "پروفایل سازمانی",
      previewFallback: "شرکت جدید",
      sideDescription:
        "اطلاعات این فرم هسته پروفایل ۳۶۰ درجه شرکت را می‌سازد و در فرآیندهای فروش استفاده می‌شود.",
      qualityTitle: "ثبت داده با کیفیت",
      qualityDescription:
        "نام حقوقی دقیق و اطلاعات تماس معتبر، جستجو و گزارش‌گیری CRM را قابل‌اعتمادتر می‌کند.",
      journey: {
        identity: "هویت شرکت",
        identityHint: "نام، نوع مالکیت و وضعیت فعالیت",
        market: "بازار و ارتباط",
        marketHint: "صنعت، اولویت، منبع و اطلاعات تماس",
        legal: "اطلاعات ثبتی",
        legalHint: "شناسه‌ها، تاریخ تأسیس و اندازه سازمان",
      },
      sections: {
        identity: "هویت و وضعیت سازمان",
        identityDescription:
          "اطلاعاتی که شرکت را در سطح سازمانی و عملیاتی تعریف می‌کند.",
        market: "پروفایل بازار و ارتباط",
        marketDescription:
          "اطلاعات موردنیاز تیم فروش برای شناخت و برقراری ارتباط با حساب.",
        legal: "اطلاعات ثبتی و اندازه شرکت",
        legalDescription:
          "مشخصات حقوقی و داده‌های سازمانی برای شناخت دقیق‌تر مشتری.",
      },
      fields: {
        legalName: "نام حقوقی",
        brandName: "نام تجاری",
        industry: "صنعت",
        ownership: "نوع مالکیت",
        priority: "اولویت حساب",
        source: "منبع ورود",
        city: "شهر / استان",
        phone: "تلفن مرکزی",
        website: "وب‌سایت",
        activityStatus: "وضعیت فعالیت",
        registrationNumber: "شماره ثبت",
        nationalId: "شناسه ملی",
        economicCode: "کد اقتصادی",
        establishmentDate: "تاریخ تأسیس",
        employeeCount: "تعداد پرسنل",
        registeredCapital: "سرمایه ثبتی",
      },
      placeholders: {
        legalName: "مثلاً شرکت ره‌آورد سامانه‌های امن",
        brandName: "نام تجاری یا نام شناخته‌شده",
        industry: "مثلاً فناوری اطلاعات",
        source: "مثلاً معرفی، رویداد یا وب‌سایت",
        city: "مثلاً تهران",
        phone: "+982112345678",
        website: "https://example.com",
        establishmentDate: "انتخاب تاریخ تأسیس",
      },
      validation: {
        legalNameRequired: "نام حقوقی الزامی است",
        invalidPhone: "شماره تماس معتبر نیست",
        invalidCapital: "سرمایه ثبتی باید عدد معتبر باشد",
        invalidEmployeeCount: "تعداد پرسنل باید عدد صحیح باشد",
      },
      selectPlaceholder: "انتخاب کنید",
      priorities: {
        LOW: "کم",
        MEDIUM: "متوسط",
        HIGH: "زیاد",
        STRATEGIC: "استراتژیک",
      },
      ownerships: {
        PRIVATE: "خصوصی",
        STATE: "دولتی",
        SEMI_STATE: "نیمه‌دولتی",
        PUBLIC_LISTED: "بورسی",
        BANK: "بانک",
        HOLDING: "هلدینگ",
      },
      activityStatuses: {
        ACTIVE: "فعال",
        INACTIVE: "غیرفعال",
        MERGED: "ادغام‌شده",
        UNKNOWN: "نامشخص",
      },
      unsavedHint: "تغییرات ثبت‌نشده دارید.",
      savedStateHint: "فرم آماده ثبت اطلاعات است.",
      submitError:
        "ثبت اطلاعات شرکت انجام نشد. اطلاعات واردشده را بررسی و دوباره تلاش کنید.",
    },
  },

  opportunities: {
    hero: {
      badge: "فضای کار فروش",
      title: "فرصت‌های فروش",
      description:
        "فرصت‌ها را در تمام چرخه فروش، از کشف تا نتیجه نهایی، در یک فضای یکپارچه مدیریت کنید.",
    },
    views: { pipeline: "پایپ‌لاین", list: "فهرست" },
    actions: {
      create: "ایجاد فرصت",
      view: "مشاهده",
      edit: "ویرایش",
      changeOwner: "تغییر مسئول",
      changeStage: "تغییر مرحله",
      archive: "بایگانی",
      restore: "بازیابی",
      more: "عملیات بیشتر",
      loadMore: "بارگذاری بیشتر",
      save: "ذخیره",
      saving: "در حال ذخیره...",
      apply: "اعمال فیلتر",
    },
    filters: {
      search: "جستجوی فرصت یا شرکت...",
      ownership: "دامنه مالکیت",
      all: "همه",
      mine: "فرصت‌های من",
      teamMine: "تیم من",
      unassigned: "بدون مسئول",
      company: "شرکت",
      priority: "اولویت",
      closeDate: "تاریخ بستن",
      more: "فیلترهای بیشتر",
      team: "تیم",
      teamPlaceholder: "نام یا کد تیم",
      owner: "مسئول",
      stage: "مرحله",
      source: "منبع",
      primaryContact: "مخاطب اصلی",
      archiveState: "وضعیت بایگانی",
      active: "فعال",
      archived: "بایگانی‌شده",
      allArchive: "همه وضعیت‌ها",
      fromDate: "از تاریخ",
      toDate: "تا تاریخ",
      allOptions: "همه",
      clear: "پاک کردن فیلترها",
      activeCount: "فیلتر فعال",
    },
    priorities: {
      LOW: "کم",
      MEDIUM: "متوسط",
      HIGH: "زیاد",
      STRATEGIC: "راهبردی",
    },
    fields: {
      title: "عنوان فرصت",
      company: "شرکت",
      primaryContact: "مخاطب اصلی",
      owner: "مسئول فرصت",
      defaultOwner: "مسئول پیش‌فرض",
      noOwner: "بدون مسئول",
      stage: "مرحله فروش",
      defaultStage: "مرحله پیش‌فرض",
      priority: "اولویت",
      estimatedValue: "ارزش تخمینی",
      expectedCloseDate: "تاریخ پیش‌بینی بستن",
      source: "منبع ایجاد فرصت",
      probability: "احتمال موفقیت",
      probabilityHint: "درصدی بین ۰ تا ۱۰۰",
      competitor: "رقیب احتمالی",
      description: "شرح نیازمندی یا توضیحات",
      note: "یادداشت اختیاری",
      status: "وضعیت",
      actions: "عملیات",
      valueUnit: "ریال",
      selectPlaceholder: "انتخاب کنید",
    },
    form: {
      createTitle: "فرصت فروش جدید",
      createDescription: "حساب مرجع و اطلاعات اولیه فرصت را ثبت کنید.",
      editTitle: "ویرایش فرصت فروش",
      editDescription:
        "اطلاعات فرصت را بدون تغییر مسئول یا مرحله به‌روزرسانی کنید.",
      companyRequired: "انتخاب شرکت الزامی است.",
      titleRequired: "عنوان فرصت الزامی است.",
      invalidProbability: "احتمال موفقیت باید بین ۰ تا ۱۰۰ باشد.",
      sourcesError:
        "دریافت منابع فرصت انجام نشد؛ این فیلد فعلاً در دسترس نیست.",
      peopleError: "دریافت مخاطبان این شرکت انجام نشد.",
      ownersError:
        "فهرست مسئولان در دسترس نیست. می‌توانید از مسئول پیش‌فرض استفاده کنید.",
      contactsEmpty: "برای این شرکت مخاطبی ثبت نشده است.",
      lockedCompany: "شرکت از مسیر جاری انتخاب شده است.",
    },
    dialogs: {
      ownerTitle: "تغییر مسئول فرصت",
      ownerDescription: "مسئول جدید این فرصت را انتخاب کنید.",
      stageTitle: "تغییر مرحله فرصت",
      stageDescription: "مرحله مقصد و در صورت نیاز یادداشت انتقال را ثبت کنید.",
      terminalTitle: "تأیید انتقال نهایی",
      terminalDescription:
        "این انتقال نتیجه مهمی در چرخه فروش ثبت می‌کند. در صورت نیاز یادداشت اضافه کنید.",
      archiveTitle: "بایگانی فرصت",
      archiveDescription:
        "فرصت از نماهای فعال کنار گذاشته می‌شود و بعداً قابل بازیابی است.",
      restoreTitle: "بازیابی فرصت",
      restoreDescription: "فرصت دوباره به فضای کاری فعال بازمی‌گردد.",
    },
    pipeline: {
      count: "فرصت",
      loadedValue: "ارزش موارد بارگذاری‌شده",
      partialValue: "مجموع ارزش فعلی بر اساس کارت‌های بارگذاری‌شده است.",
      dragHint: "برای تغییر مرحله بکشید",
      invalidTarget: "انتقال به این مرحله مجاز نیست",
      emptyStage: "فرصتی در این مرحله نیست.",
      emptyBoard: "فرصتی مطابق فیلترهای فعلی پیدا نشد.",
    },
    table: {
      opportunity: "فرصت",
      company: "شرکت",
      stage: "مرحله",
      estimatedValue: "ارزش تخمینی",
      probability: "احتمال",
      priority: "اولویت",
      owner: "مسئول",
      closeDate: "تاریخ بستن",
      status: "وضعیت",
    },
    status: { active: "فعال", archived: "بایگانی‌شده" },
    empty: {
      listTitle: "فرصتی پیدا نشد",
      listDescription: "فیلترها را تغییر دهید یا یک فرصت جدید ایجاد کنید.",
      stagesTitle: "مرحله فعالی تعریف نشده است",
      stagesDescription:
        "پیکربندی مراحل پایپ‌لاین برای نمایش این فضا لازم است.",
    },
    errors: {
      permissionTitle: "دسترسی مشاهده فرصت‌ها فعال نیست",
      permissionDescription:
        "برای استفاده از فضای فرصت‌ها به مجوز opportunity:view نیاز دارید.",
      listTitle: "دریافت فرصت‌ها انجام نشد",
      listDescription: "ارتباط با سرویس فرصت‌ها برقرار نشد. دوباره تلاش کنید.",
      stagesTitle: "دریافت مراحل پایپ‌لاین انجام نشد",
      stagesDescription: "مرحله‌های فعال از سرویس پایپ‌لاین دریافت نشدند.",
      transitions: "قوانین انتقال دریافت نشد؛ جابه‌جایی با کشیدن غیرفعال است.",
      mutation: "عملیات فرصت انجام نشد.",
      stageMutation: "تغییر مرحله انجام نشد و کارت به جای قبلی بازگشت.",
      ownerMutation: "تغییر مسئول فرصت انجام نشد.",
      ownerOptionsPermission:
        "فهرست مسئولان به دلیل محدودیت دسترسی در دسترس نیست.",
    },
    feedback: {
      created: "فرصت ایجاد شد.",
      updated: "فرصت به‌روزرسانی شد.",
      stageChanged: "مرحله فرصت تغییر کرد.",
      ownerChanged: "مسئول فرصت تغییر کرد.",
      archived: "فرصت بایگانی شد.",
      restored: "فرصت بازیابی شد.",
    },
    detail: {
      back: "بازگشت به فضای فرصت‌ها",
      cockpit: "مرکز اجرای فروش",
      nav: {
        overview: "نمای کلی",
        commercial: "تجاری",
        execution: "اجرا",
        files: "فایل‌ها و تاریخچه",
      },
      summary: {
        commercial: "ارزش تجاری",
        estimated: "ارزش تخمینی",
        weighted: "ارزش وزنی محاسبه‌شده",
        probability: "احتمال موفقیت",
        timing: "زمان‌بندی",
        remaining: "زمان تا بستن",
        overdue: "گذشته از موعد",
        days: "روز",
        today: "امروز",
        engagement: "تعامل کلیدی",
        activity: "آخرین فعالیت",
        noActivity: "فعالیتی ثبت نشده",
      },
      progress: {
        title: "موقعیت در مسیر فروش",
        current: "مرحله فعلی",
        visited: "دارای سابقه ورود",
        terminal: "مرحله نهایی",
      },
      sections: {
        overview: "خلاصه فرصت",
        description: "شرح فرصت",
        businessContext: "زمینه تجاری",
        recentActivity: "فعالیت‌های اخیر",
        company: "حساب / شرکت",
        contact: "مخاطب اصلی",
        ownership: "مسئولیت و زمان‌بندی",
        lineItems: "اقلام فرصت",
        documents: "اسناد تجاری",
        payments: "پرداخت‌ها",
        tasks: "کارهای این فرصت",
        meetings: "جلسات این فرصت",
        attachments: "پیوست‌های فرصت",
        stageHistory: "تاریخچه مراحل",
        activityHistory: "تاریخچه فعالیت",
      },
      fields: {
        industry: "صنعت",
        source: "منبع فرصت",
        competitor: "رقیب",
        createdAt: "تاریخ ایجاد",
        updatedAt: "آخرین بروزرسانی",
        owner: "مسئول فرصت",
        team: "تیم مسئول",
        contactTitle: "سمت",
        department: "دپارتمان",
        email: "ایمیل",
        phone: "تلفن",
        fromStage: "از مرحله",
        toStage: "به مرحله",
        changedBy: "تغییردهنده",
        changedAt: "زمان تغییر",
        product: "محصول یا خدمت",
        customItem: "قلم سفارشی",
        quantity: "تعداد",
        unit: "واحد",
        unitPrice: "قیمت واحد",
        discount: "تخفیف",
        tax: "مالیات",
        total: "مبلغ کل",
        salesChannel: "کانال فروش",
        sortOrder: "ترتیب نمایش",
        documentType: "نوع سند",
        documentStatus: "وضعیت سند",
        documentNumber: "شماره سند",
        documentTitle: "عنوان سند",
        version: "نسخه",
        amount: "مبلغ",
        currency: "ارز",
        validUntil: "اعتبار تا",
        issuedAt: "تاریخ صدور",
        file: "فایل",
        fileHint: "حداکثر حجم فایل ۲۵ مگابایت",
        selectedFile: "فایل انتخاب‌شده",
        paymentStatus: "وضعیت پرداخت",
        dueDate: "سررسید",
        paidAt: "تاریخ پرداخت",
        method: "روش پرداخت",
        reference: "شماره پیگیری",
        linkedDocument: "سند مرتبط",
        relatedPayments: "پرداخت مرتبط",
        taskTitle: "عنوان کار",
        taskStatus: "وضعیت کار",
        dueAt: "موعد انجام",
        meetingTitle: "عنوان جلسه",
        meetingMode: "نوع جلسه",
        startAt: "شروع جلسه",
        endAt: "پایان جلسه",
        location: "محل جلسه",
        meetingUrl: "پیوند جلسه",
        agenda: "دستور جلسه",
        attachmentDescription: "توضیح فایل",
        fileSize: "حجم",
        notes: "یادداشت",
      },
      actions: {
        company: "مشاهده شرکت",
        contact: "مشاهده پروفایل فرد",
        addLineItem: "افزودن قلم",
        addDocument: "افزودن سند مالی",
        uploadDocument: "افزودن سند قراردادی",
        addPayment: "ثبت پرداخت",
        markPaid: "ثبت به‌عنوان پرداخت‌شده",
        cancelPayment: "لغو پرداخت",
        addTask: "ایجاد کار",
        completeTask: "تکمیل کار",
        addMeeting: "ایجاد جلسه",
        completeMeeting: "تکمیل جلسه",
        cancelMeeting: "لغو جلسه",
        uploadAttachment: "بارگذاری پیوست",
        download: "دانلود",
        changeStatus: "تغییر وضعیت",
        delete: "حذف",
      },
      empty: {
        description: "توضیحی برای این فرصت ثبت نشده است.",
        contact: "مخاطب اصلی برای این فرصت انتخاب نشده است.",
        activities: "فعالیت اخیری برای این فرصت ثبت نشده است.",
        lineItems: "قلم تجاری برای این فرصت ثبت نشده است.",
        documents: "سند تجاری برای این فرصت ثبت نشده است.",
        payments: "پرداختی برای این فرصت ثبت نشده است.",
        tasks: "کاری برای این فرصت ثبت نشده است.",
        meetings: "جلسه‌ای برای این فرصت ثبت نشده است.",
        attachments: "پیوستی برای این فرصت ثبت نشده است.",
        stageHistory: "سابقه تغییر مرحله‌ای ثبت نشده است.",
      },
      errors: {
        title: "دریافت جزئیات فرصت انجام نشد",
        description: "اطلاعات اصلی فرصت در دسترس نیست. دوباره تلاش کنید.",
        section: "دریافت اطلاعات این بخش انجام نشد.",
        mutation: "ثبت تغییرات انجام نشد.",
        fileTooLarge: "حجم فایل بیشتر از ۲۵ مگابایت است.",
        fileRequired: "انتخاب فایل الزامی است.",
        endBeforeStart: "زمان پایان باید بعد از زمان شروع باشد.",
        resourcePermissionTitle: "دسترسی این بخش فعال نیست",
        resourcePermissionDescription:
          "برای مشاهده یا مدیریت این بخش، مجوز مرتبط باید در حساب شما فعال باشد.",
      },
      dialogs: {
        lineItemCreate: "افزودن قلم فرصت",
        lineItemEdit: "ویرایش قلم فرصت",
        documentCreate: "افزودن سند تجاری",
        documentEdit: "ویرایش سند تجاری",
        paymentCreate: "ثبت پرداخت",
        paymentEdit: "ویرایش پرداخت",
        taskCreate: "ایجاد کار مرتبط",
        taskEdit: "ویرایش کار مرتبط",
        meetingCreate: "ایجاد جلسه مرتبط",
        meetingEdit: "ویرایش جلسه مرتبط",
        attachmentUpload: "بارگذاری پیوست",
        deleteTitle: "تأیید حذف",
        deleteDescription: "این مورد حذف می‌شود و بازگردانی آن ممکن نیست.",
        completeTitle: "تأیید تکمیل",
        cancelTitle: "تأیید لغو",
        statusTitle: "تغییر وضعیت سند",
      },
      activityTypes: {
        CALL: "تماس",
        EMAIL: "ایمیل",
        LINKEDIN_MESSAGE: "پیام لینکدین",
        LINKEDIN_ENGAGEMENT: "تعامل لینکدین",
        MEETING: "جلسه",
        NOTE: "یادداشت",
        STAGE_CHANGE: "تغییر مرحله",
      },
      documentTypes: {
        PROPOSAL: "پیشنهاد",
        PROFORMA: "پیش‌فاکتور",
        CONTRACT: "قرارداد",
      },
      documentStatuses: {
        DRAFT: "پیش‌نویس",
        SENT: "ارسال‌شده",
        ACCEPTED: "پذیرفته‌شده",
        REJECTED: "ردشده",
        SIGNED: "امضاشده",
        CANCELLED: "لغوشده",
        EXPIRED: "منقضی‌شده",
      },
      paymentStatuses: {
        PENDING: "در انتظار",
        PARTIAL: "پرداخت جزئی",
        PAID: "پرداخت‌شده",
        OVERDUE: "سررسید گذشته",
        CANCELLED: "لغوشده",
        REFUNDED: "بازپرداخت‌شده",
      },
      paymentMethods: {
        BANK_TRANSFER: "انتقال بانکی",
        CASH: "نقدی",
        CHECK: "چک",
        CARD: "کارت",
        OTHER: "سایر",
      },
      paymentSummary: {
        total: "جمع پرداخت‌ها",
        paid: "مبلغ پرداخت‌شده",
        unpaid: "مانده پرداخت",
        overdue: "تعداد سررسید گذشته",
      },
      taskStatuses: {
        TODO: "انجام‌نشده",
        IN_PROGRESS: "در حال انجام",
        DONE: "انجام‌شده",
        CANCELLED: "لغوشده",
      },
      meetingStatuses: {
        SCHEDULED: "برنامه‌ریزی‌شده",
        COMPLETED: "تکمیل‌شده",
        CANCELLED: "لغوشده",
      },
      meetingModes: { IN_PERSON: "حضوری", ONLINE: "آنلاین", HYBRID: "ترکیبی" },
      salesChannels: {
        IN_PERSON: "فروش حضوری",
        DIGIKALA: "دیجی‌کالا",
        OTHER: "سایر",
        LEGACY_UNKNOWN: "نامشخص قدیمی",
      },
      fileUnits: { bytes: "بایت", kilobytes: "کیلوبایت", megabytes: "مگابایت" },
      feedback: {
        saved: "اطلاعات با موفقیت ثبت شد.",
        deleted: "مورد انتخاب‌شده حذف شد.",
        uploaded: "فایل با موفقیت بارگذاری شد.",
        downloaded: "دانلود فایل آغاز شد.",
      },
    },
  },

tasks: {
  title: "کارها",
  description:
    "فضای اجرای کارهای روزانه، پیگیری موعدها و مدیریت اقدام‌های مرتبط با فروش",
  views: { focus: "تمرکز", list: "فهرست" },
  quick: {
    all: "همه",
    overdue: "سررسید گذشته",
    todo: "انجام‌نشده",
    inProgress: "در حال انجام",
    done: "انجام‌شده",
    cancelled: "لغوشده",
    mine: "کارهای من",
    created: "ایجادشده توسط من",
  },
  statuses: {
    TODO: "انجام‌نشده",
    IN_PROGRESS: "در حال انجام",
    DONE: "انجام‌شده",
    CANCELLED: "لغوشده",
  },
  priorities: {
    LOW: "کم",
    MEDIUM: "متوسط",
    HIGH: "زیاد",
    STRATEGIC: "راهبردی",
  },
  actions: {
    create: "ایجاد کار",
    edit: "ویرایش",
    save: "ذخیره",
    more: "عملیات بیشتر",
    changeStatus: "تغییر وضعیت",
    assign: "ارجاع",
    complete: "تکمیل",
    reschedule: "زمان‌بندی مجدد",
    delete: "حذف",
    filters: "فیلترها",
    clearFilters: "پاک کردن فیلترها",
    clearSelection: "حذف انتخاب",
    loadMore: "نمایش بیشتر",
    apply: "اعمال",
  },
  fields: {
    title: "عنوان کار",
    description: "توضیحات",
    priority: "اولویت",
    status: "وضعیت",
    company: "شرکت",
    opportunity: "فرصت",
    person: "مخاطب",
    commercialDocument: "سند تجاری",
    payment: "پرداخت",
    assignee: "مسئول",
    dueAt: "موعد انجام",
    reminderAt: "زمان یادآوری",
    completionNote: "یادداشت تکمیل",
    note: "یادداشت",
  },
  sections: {
    task: "تعریف کار",
    taskDescription: "عنوان، توضیحات و سطح اولویت کار را مشخص کنید.",
    context: "زمینه تجاری",
    contextDescription:
      "کار را در صورت نیاز به شرکت، فرصت، مخاطب، سند یا پرداخت مرتبط کنید.",
    ownership: "مسئولیت",
    ownershipDescription:
      "مسئول اجرای کار را تعیین کنید؛ در صورت خالی بودن، سیاست پیش‌فرض Backend اعمال می‌شود.",
    schedule: "زمان‌بندی",
    scheduleDescription: "موعد انجام و زمان یادآوری کار را تنظیم کنید.",
  },
  groups: {
    overdue: "نیازمند اقدام فوری",
    active: "در جریان",
    closed: "بسته‌شده",
  },
  labels: {
    overdue: "از موعد گذشته",
    noDueDate: "بدون موعد",
    unassigned: "بدون مسئول",
  },
  table: {
    task: "کار",
    status: "وضعیت",
    priority: "اولویت",
    assignee: "مسئول",
    dueAt: "سررسید",
    reminderAt: "یادآوری",
    actions: "عملیات",
  },
  filters: {
    allPriorities: "همه اولویت‌ها",
    dueFrom: "سررسید از",
    dueTo: "سررسید تا",
  },
  placeholders: {
    search: "جستجو در عنوان، توضیحات، شرکت، فرصت یا مخاطب...",
    searchOptions: "جستجو...",
    loading: "در حال دریافت...",
    noOptions: "موردی برای نمایش وجود ندارد.",
    company: "انتخاب شرکت",
    companyFirst: "ابتدا شرکت را انتخاب کنید",
    opportunity: "انتخاب فرصت",
    opportunityFirst: "ابتدا فرصت را انتخاب کنید",
    person: "انتخاب مخاطب",
    commercialDocument: "انتخاب سند تجاری",
    payment: "انتخاب پرداخت",
    assignee: "انتخاب مسئول",
    systemAssignee: "پیش‌فرض سیستم",
  },
  fallbacks: {
    opportunity: "فرصت",
    person: "مخاطب",
    document: "سند تجاری",
    payment: "پرداخت",
  },
  validation: {
    titleRequired: "عنوان کار الزامی است.",
    reminderBeforeDue: "زمان یادآوری باید قبل از موعد انجام باشد.",
    companyForPerson: "برای انتخاب مخاطب، ابتدا شرکت را مشخص کنید.",
    opportunityForCommercialContext:
      "برای انتخاب سند تجاری یا پرداخت، ابتدا فرصت را مشخص کنید.",
  },
  dialogs: {
    createTitle: "ایجاد کار",
    editTitle: "ویرایش کار",
    formDescription:
      "کار، زمینه تجاری، مسئول و زمان‌بندی را در یک جریان یکپارچه ثبت کنید.",
    completeTitle: "تکمیل کار",
    completeDescription: "در صورت نیاز نتیجه یا توضیح تکمیل کار را ثبت کنید.",
    statusTitle: "تغییر وضعیت کار",
    statusDescription:
      "وضعیت جدید را انتخاب کنید. یادداشت اختیاری در رویداد ممیزی ثبت می‌شود.",
    assignTitle: "ارجاع کار",
    assignDescription: "یک کاربر داخلی مجاز را به‌عنوان مسئول کار انتخاب کنید.",
    rescheduleTitle: "زمان‌بندی مجدد",
    rescheduleDescription: "موعد جدید و در صورت نیاز زمان یادآوری را مشخص کنید.",
    deleteTitle: "حذف کار",
    deleteDescription:
      "این کار حذف می‌شود و عملیات قابل بازگشت نیست. در صورت اطمینان ادامه دهید.",
  },
  feedback: {
    created: "کار با موفقیت ایجاد شد.",
    updated: "کار با موفقیت بروزرسانی شد.",
    completed: "کار تکمیل شد.",
    statusChanged: "وضعیت کار تغییر کرد.",
    assigned: "کار با موفقیت ارجاع شد.",
    rescheduled: "زمان‌بندی کار بروزرسانی شد.",
    deleted: "کار حذف شد.",
  },
  empty: {
    title: "کاری برای نمایش وجود ندارد",
    description:
      "فیلترها را تغییر دهید یا در صورت داشتن مجوز، یک کار جدید ایجاد کنید.",
  },
  errors: {
    permissionTitle: "دسترسی مشاهده کارها فعال نیست",
    permissionDescription:
      "برای مشاهده این بخش به مجوز task:view نیاز دارید.",
    listTitle: "دریافت کارها انجام نشد",
    listDescription:
      "در حال حاضر امکان دریافت فهرست کارها از سرور وجود ندارد. دوباره تلاش کنید.",
    mutation: "عملیات کار انجام نشد.",
  },
  detail: {
    description:
      "نمایش جزئیات کار، زمینه تجاری، مسئولیت و چرخه اجرای کار.",
    actions: {
      back: "بازگشت به کارها",
    },
    sections: {
      schedule: "زمان‌بندی",
      description: "توضیحات",
      outcome: "نتیجه انجام کار",
      cancellation: "اطلاعات لغو",
      context: "زمینه تجاری",
      ownership: "مسئولیت",
      lifecycle: "چرخه کار",
    },
    labels: {
      due: "موعد انجام",
      reminder: "یادآوری",
      noReminder: "بدون یادآوری",
      assignee: "مسئول اجرا",
      createdBy: "ایجادکننده",
      completedBy: "تکمیل‌کننده",
      company: "شرکت",
      opportunity: "فرصت",
      person: "مخاطب",
      document: "سند تجاری",
      payment: "پرداخت",
    },
    lifecycle: {
      created: "ایجاد کار",
      updated: "آخرین بروزرسانی",
      completed: "تکمیل کار",
      cancelled: "لغو کار",
    },
    empty: {
      description: "توضیحی برای این کار ثبت نشده است.",
      completionNote: "یادداشت تکمیل ثبت نشده است.",
      cancelReason: "دلیل لغو ثبت نشده است.",
      activeOutcome: "نتیجه انجام کار پس از تکمیل نمایش داده می‌شود.",
    },
    errors: {
      loadTitle: "دریافت کار انجام نشد",
      loadDescription:
        "اطلاعات کار از سرویس دریافت نشد. دوباره تلاش کنید.",
    },
  },
},
  meetings: {
    title: "جلسات",
    description: "برنامه‌ریزی و پیگیری تعاملات فروش و جلسات پیش‌رو",
    views: { agenda: "دستور کار", list: "فهرست" },
    actions: {
      create: "جلسه جدید",
      edit: "ویرایش جلسه",
      complete: "ثبت به‌عنوان برگزارشده",
      cancel: "لغو جلسه",
      save: "ذخیره جلسه",
      more: "عملیات جلسه",
      filters: "فیلترهای بیشتر",
      clear: "پاک کردن فیلترها",
      loadMore: "نمایش موارد بیشتر",
    },
    quickFilters: {
      all: "همه",
      today: "امروز",
      upcoming: "پیش‌رو",
      mine: "جلسات من",
      completed: "برگزارشده",
      cancelled: "لغوشده",
      past: "گذشته",
    },
    statuses: {
      SCHEDULED: "برنامه‌ریزی‌شده",
      COMPLETED: "برگزارشده",
      CANCELLED: "لغوشده",
    },
    modes: { IN_PERSON: "حضوری", ONLINE: "آنلاین", HYBRID: "ترکیبی" },
    relativeDays: { today: "امروز", tomorrow: "فردا", yesterday: "دیروز" },
    fields: {
      search: "جستجوی جلسه، شرکت یا فرصت",
      company: "شرکت",
      opportunity: "فرصت",
      status: "وضعیت",
      mode: "نوع برگزاری",
      type: "نوع جلسه",
      dateRange: "بازه تاریخ",
      organizer: "برگزارکننده",
      assignedUser: "مسئول داخلی",
      attendee: "مدعو شرکت",
      title: "عنوان جلسه",
      agenda: "دستور جلسه",
      description: "توضیحات",
      startAt: "شروع جلسه",
      endAt: "پایان جلسه",
      reminder: "یادآوری",
      customReminder: "زمان دلخواه یادآوری",
      location: "محل جلسه",
      meetingUrl: "پیوند جلسه",
      assignees: "مسئولان داخلی",
      attendees: "مدعوین شرکت",
      schedule: "زمان‌بندی",
      meeting: "جلسه",
      actions: "عملیات",
    },
    sections: {
      context: "زمینه جلسه",
      contextDescription: "شرکت و فرصت مرتبط با جلسه را مشخص کنید.",
      meeting: "اطلاعات جلسه",
      meetingDescription: "عنوان، دستور و توضیحات جلسه را ثبت کنید.",
      schedule: "زمان‌بندی و یادآوری",
      scheduleDescription: "زمان شروع، پایان و یادآوری را تنظیم کنید.",
      delivery: "شیوه برگزاری",
      deliveryDescription: "نوع برگزاری و اطلاعات ورود یا محل را مشخص کنید.",
      people: "افراد جلسه",
      peopleDescription: "مسئولان داخلی و مدعوین شرکت را انتخاب کنید.",
    },
    reminders: {
      none: "بدون یادآوری",
      minutes15: "۱۵ دقیقه قبل",
      minutes30: "۳۰ دقیقه قبل",
      hour1: "۱ ساعت قبل",
      hours2: "۲ ساعت قبل",
      day1: "۱ روز قبل",
      custom: "زمان دلخواه",
    },
    placeholders: {
      select: "انتخاب کنید",
      companyFirst: "ابتدا شرکت را انتخاب کنید",
      searchOptions: "جستجو در گزینه‌ها...",
      noOptions: "گزینه‌ای پیدا نشد.",
      loading: "در حال دریافت گزینه‌ها...",
      selectedCount: "مورد انتخاب شده",
      optionalNote: "یادداشت اختیاری",
    },
    agenda: {
      assignees: "مسئول",
      attendees: "مدعو",
      online: "جلسه آنلاین",
    },
    table: {
      company: "شرکت",
      schedule: "زمان‌بندی",
      mode: "نوع برگزاری",
      type: "نوع جلسه",
      owner: "برگزارکننده / مسئولان",
      status: "وضعیت",
    },
    dialogs: {
      createTitle: "ایجاد جلسه جدید",
      editTitle: "ویرایش جلسه",
      completeTitle: "ثبت برگزاری جلسه",
      completeDescription: "این جلسه به‌عنوان برگزارشده ثبت می‌شود.",
      cancelTitle: "لغو جلسه",
      cancelDescription: "این جلسه لغو می‌شود و دیگر قابل ویرایش نخواهد بود.",
      companyChangeTitle: "تغییر شرکت جلسه",
      companyChangeDescription:
        "با تغییر شرکت، فرصت و مدعوین انتخاب‌شده پاک می‌شوند.",
    },
    validation: {
      companyRequired: "انتخاب شرکت الزامی است.",
      opportunityRequiredAfterCompanyChange:
        "برای تغییر شرکت این جلسه، یک فرصت متعلق به شرکت جدید انتخاب کنید.",
      titleRequired: "عنوان جلسه الزامی است.",
      startRequired: "زمان شروع جلسه الزامی است.",
      endRequired: "زمان پایان جلسه الزامی است.",
      endAfterStart: "زمان پایان باید بعد از زمان شروع باشد.",
      reminderRequired: "زمان دلخواه یادآوری را انتخاب کنید.",
      reminderBeforeStart: "زمان یادآوری باید قبل از شروع جلسه باشد.",
      reminderPast: "یادآوری جلسه آینده نمی‌تواند در گذشته باشد.",
      urlInvalid: "پیوند جلسه باید با http یا https شروع شود.",
    },
    detail: {
      actions: {
        back: "بازگشت به جلسات",
        join: "ورود به جلسه",
        uploadAttachment: "افزودن صورتجلسه یا مستند",
        download: "دانلود",
        deleteAttachment: "حذف مستند",
      },
      sections: {
        schedule: "زمان و نحوه برگزاری",
        context: "زمینه تجاری",
        people: "افراد جلسه",
        agenda: "دستور جلسه",
        description: "توضیحات",
        outcome: "نتیجه جلسه",
        cancellation: "اطلاعات لغو",
        attachments: "صورتجلسه و مستندات",
        lifecycle: "چرخه جلسه",
      },
      labels: {
        date: "تاریخ",
        time: "ساعت",
        mode: "نوع برگزاری",
        type: "نوع جلسه",
        reminder: "یادآوری",
        noReminder: "بدون یادآوری",
        location: "محل جلسه",
        meetingUrl: "پیوند جلسه",
        company: "شرکت",
        opportunity: "فرصت",
        organizer: "برگزارکننده",
        assignees: "مسئولان داخلی",
        attendees: "مدعوین شرکت",
      },
      lifecycle: {
        created: "ایجاد جلسه",
        updated: "آخرین به‌روزرسانی",
        completed: "ثبت برگزاری",
        cancelled: "ثبت لغو",
      },
      empty: {
        agenda: "دستور جلسه‌ای ثبت نشده است.",
        description: "توضیحی برای این جلسه ثبت نشده است.",
        outcomeScheduled:
          "پس از ثبت جلسه به‌عنوان برگزارشده، نتیجه جلسه در این بخش نمایش داده می‌شود.",
        completionNote: "یادداشت نتیجه‌ای برای جلسه ثبت نشده است.",
        cancellationReason: "دلیلی برای لغو جلسه ثبت نشده است.",
      },
      attachments: {
        scheduledHint:
          "پس از ثبت جلسه به‌عنوان برگزارشده، امکان بارگذاری صورتجلسه و مستندات جلسه فعال می‌شود.",
        cancelledHint:
          "این جلسه لغو شده است و امکان بارگذاری صورتجلسه یا مستند برای آن وجود ندارد.",
        completedHint:
          "صورتجلسه، فایل‌های ارائه‌شده و مستندات مرتبط با جلسه را در این بخش نگهداری کنید.",
        emptyTitle: "هنوز مستندی ثبت نشده است",
        emptyDescription:
          "صورتجلسه یا فایل مرتبط با این جلسه را اضافه کنید.",
        fileLabel: "فایل",
        fileHint: "حداکثر اندازه فایل ۲۵ مگابایت است.",
        descriptionLabel: "عنوان یا توضیح فایل",
        fileTooLarge: "حجم فایل نباید بیشتر از ۲۵ مگابایت باشد.",
      },
      dialogs: {
        uploadTitle: "افزودن صورتجلسه یا مستند",
        uploadDescription:
          "فایل مرتبط با جلسه را همراه با توضیح اختیاری بارگذاری کنید.",
        deleteAttachmentTitle: "حذف مستند جلسه",
        deleteAttachmentDescription:
          "این فایل از مستندات جلسه حذف می‌شود. این عملیات قابل بازگشت نیست.",
      },
      feedback: {
        uploaded: "مستند جلسه با موفقیت بارگذاری شد.",
        downloaded: "دانلود فایل آغاز شد.",
        deleted: "مستند جلسه حذف شد.",
      },
      errors: {
        permissionTitle: "دسترسی مشاهده جلسه فعال نیست",
        permissionDescription:
          "برای مشاهده جزئیات این جلسه به مجوز meeting:view نیاز دارید.",
        loadTitle: "دریافت جزئیات جلسه انجام نشد",
        loadDescription:
          "اطلاعات جلسه در دسترس نیست. دوباره تلاش کنید.",
        attachmentPermissionTitle: "دسترسی مشاهده مستندات فعال نیست",
        attachmentPermissionDescription:
          "برای مشاهده صورتجلسه و مستندات به مجوز attachment:view نیاز دارید.",
        attachmentLoad: "دریافت مستندات جلسه انجام نشد",
        attachmentLoadDescription:
          "فهرست مستندات جلسه در دسترس نیست. دوباره تلاش کنید.",
        attachmentMutation: "ثبت تغییرات مستندات جلسه انجام نشد.",
      },
      fileUnits: {
        bytes: "بایت",
        kilobytes: "کیلوبایت",
        megabytes: "مگابایت",
      },
    },
    empty: {
      title: "جلسه‌ای پیدا نشد",
      description: "فیلترها را تغییر دهید یا جلسه جدیدی ایجاد کنید.",
      today: "برای امروز جلسه‌ای ثبت نشده است.",
      upcoming: "جلسه پیش‌رویی پیدا نشد.",
    },
    errors: {
      listTitle: "دریافت جلسات انجام نشد",
      listDescription: "ارتباط با سرویس جلسات برقرار نشد. دوباره تلاش کنید.",
      mutation: "ثبت تغییرات جلسه انجام نشد.",
      options: "دریافت گزینه‌ها انجام نشد.",
    },
    feedback: {
      created: "جلسه ایجاد شد.",
      updated: "جلسه به‌روزرسانی شد.",
      completed: "جلسه به‌عنوان برگزارشده ثبت شد.",
      cancelled: "جلسه لغو شد.",
    },
  },

  people: {
    hero: {
      badge: "فضای هوشمند ارتباط با افراد",
      title: "افراد و ارتباطات",
      description:
        "نمایی یکپارچه از تصمیم‌گیرندگان، مخاطبان کلیدی و شبکه ارتباطی مشتریان برای دسترسی سریع‌تر به زمینه فروش.",
    },
    actions: {
      create: "افزودن فرد",
      edit: "ویرایش",
      delete: "حذف",
      save: "ذخیره تغییرات",
      close: "بستن",
      add: "افزودن",
      retry: "تلاش دوباره",
    },
    feedback: {
      created: "فرد با موفقیت ایجاد شد.",
    },
    metrics: {
      total: "کل افراد",
      primaryCurrentPage: "مخاطب اصلی در این صفحه",
      phoneCurrentPage: "دارای تلفن در این صفحه",
      emailCurrentPage: "دارای ایمیل در این صفحه",
      currentPageHint: "بر اساس صفحه جاری",
    },
    filters: {
      searchPlaceholder: "جستجو در نام، سمت، شرکت، ایمیل یا تلفن...",
      allCompanies: "همه شرکت‌ها",
      allJobTitles: "همه سمت‌های سازمانی",
      allDepartments: "همه دپارتمان‌ها",
      allPersonaRoles: "همه نقش‌ها در فرآیند خرید",
      allSeniorityLevels: "همه سطوح ارشدیت",
      jobTitle: "سمت سازمانی",
      department: "دپارتمان",
      allContactRoles: "همه مخاطبان",
      notPrimary: "غیر اصلی",
      quickFilters: "فیلتر سریع",
      hasPhone: "دارای تلفن",
      hasEmail: "دارای ایمیل",
    },
    companySelect: {
      placeholder: "انتخاب شرکت",
      searchPlaceholder: "جستجو در نام شرکت، شناسه ملی یا شماره ثبت...",
      loading: "در حال دریافت شرکت‌ها...",
      empty: "شرکتی مطابق جستجو پیدا نشد.",
      clear: "همه شرکت‌ها",
      firstTenHint:
        "حداکثر ۱۰ نتیجه نمایش داده می‌شود؛ برای یافتن شرکت‌های دیگر جستجو کنید.",
    },

    contactRole: {
      normal: "مخاطب عادی",
      primary: "مخاطب اصلی",
      secondary: "مخاطب دوم",
      primaryShort: "اصلی",
    },
    fields: {
      fullName: "نام کامل",
      company: "شرکت",
      jobTitle: "سمت سازمانی",
      department: "دپارتمان",
      personaRole: "نقش در فرآیند خرید",
      seniorityLevel: "سطح ارشدیت",
      contactRole: "نقش ارتباطی",
      phone: "تلفن",
      email: "ایمیل",
      linkedin: "لینکدین",
      owner: "مالک حساب",
      ownerTeam: "تیم مالک حساب",
      createdAt: "تاریخ ایجاد",
      updatedAt: "آخرین بروزرسانی",
    },
    sections: {
      profile: "پروفایل ارتباطی",
      contacts: "راه‌های ارتباطی",
      socials: "هویت اجتماعی",
      career: "مسیر شغلی",
      education: "تحصیلات",
    },
    form: {
      createTitle: "افزودن فرد جدید",
      editTitle: "ویرایش اطلاعات فرد",
      description:
        "پروفایل ارتباطی فرد را با تمرکز بر جایگاه سازمانی، نقش در فرآیند خرید و داده‌های تماس ثبت کنید.",
      identityTitle: "هویت و جایگاه سازمانی",
      identityDescription:
        "اطلاعات اصلی فرد و جایگاه او در ساختار سازمان مشتری.",
      salesProfileTitle: "پروفایل فروش و ارتباط",
      salesProfileDescription:
        "اطلاعاتی که برای شناخت نقش فرد در فرآیند خرید و برقراری ارتباط استفاده می‌شود.",
      selectCompany: "انتخاب شرکت",
      selectJobTitle: "انتخاب سمت سازمانی",
      selectDepartment: "انتخاب دپارتمان",
      selectPersonaRole: "انتخاب نقش در فرآیند خرید",
      selectSeniority: "انتخاب سطح ارشدیت",
    },
    career: {
      current: "سمت فعلی",
      present: "اکنون",
      position: "سمت",
      companyActions: "مدیریت سابقه شرکت",
      addEmployment: "افزودن سابقه شغلی",
      addPosition: "افزودن سمت",
      editEmployment: "ویرایش سابقه شغلی",
      editPosition: "ویرایش سمت",
      companyDescription: "توضیحات همکاری با این شرکت",
      positionTitle: "عنوان سمت",
      startDate: "تاریخ شروع",
      endDate: "تاریخ پایان",
      description: "توضیحات",
      currentQuestion: "این سمت فعلی است",
      dateError: "تاریخ پایان نباید پیش از تاریخ شروع باشد.",
      deleteEmploymentTitle: "حذف سابقه شغلی",
      deleteEmploymentDescription:
        "سابقه این شرکت و تمام سمت‌های زیرمجموعه آن حذف می‌شود. ادامه می‌دهید؟",
      deletePositionTitle: "حذف سمت شغلی",
      deletePositionDescription: "آیا از حذف این سمت اطمینان دارید؟",
      noPositions: "هنوز سمتی برای این شرکت ثبت نشده است.",
    },
    contactHub: {
      title: "مرکز راه‌های تماس",
      add: "افزودن راه تماس",
      edit: "ویرایش راه تماس",
      type: "نوع راه تماس",
      selectType: "انتخاب نوع تماس",
      value: "مقدار تماس",
      note: "یادداشت",
      primary: "راه تماس اصلی",
      deleteTitle: "حذف راه تماس",
      deleteDescription: "آیا از حذف این راه تماس اطمینان دارید؟",
      types: {
        MOBILE: "موبایل",
        WORK: "تلفن کاری",
        PERSONAL_EMAIL: "ایمیل شخصی",
        WORK_EMAIL: "ایمیل کاری",
        OTHER: "سایر",
      },
    },
    socialIdentity: {
      title: "هویت اجتماعی",
      add: "افزودن شبکه اجتماعی",
      edit: "ویرایش شبکه اجتماعی",
      platform: "پلتفرم",
      selectPlatform: "انتخاب پلتفرم",
      handle: "شناسه یا نشانی",
      note: "یادداشت",
      primary: "شبکه اجتماعی اصلی",
      deleteTitle: "حذف شبکه اجتماعی",
      deleteDescription: "آیا از حذف این شبکه اجتماعی اطمینان دارید؟",
      platforms: {
        LINKEDIN: "لینکدین",
        INSTAGRAM: "اینستاگرام",
        TELEGRAM: "تلگرام",
        BALE: "بله",
        EITAA: "ایتا",
        SOROUSH: "سروش",
        ROOBIKA: "روبیکا",
        APARAT: "آپارات",
        YOUTUBE: "یوتیوب",
        WEBSITE: "وب‌سایت",
        OTHER: "سایر",
      },
    },
    education: {
      add: "افزودن سابقه تحصیلی",
      edit: "ویرایش سابقه تحصیلی",
      degree: "مقطع تحصیلی",
      selectDegree: "انتخاب مقطع",
      university: "دانشگاه",
      selectUniversity: "انتخاب دانشگاه",
      searchUniversity: "جستجوی دانشگاه...",
      educationDate: "تاریخ تحصیل یا فارغ‌التحصیلی",
      description: "توضیحات",
      deleteTitle: "حذف سابقه تحصیلی",
      deleteDescription: "آیا از حذف این سابقه تحصیلی اطمینان دارید؟",
      universityEmpty: "دانشگاهی مطابق جستجو پیدا نشد.",
      universityLoading: "در حال دریافت دانشگاه‌ها...",
      universityPermissionError:
        "فهرست دانشگاه‌ها در دسترس نیست. برای مشاهده آن به مجوز کتابخانه دانشگاه‌ها نیاز دارید.",
      degrees: {
        DIPLOMA: "دیپلم",
        ASSOCIATE: "کاردانی",
        BACHELOR: "کارشناسی",
        PHD: "دکتری",
        POSTDOC: "پسادکتری",
      },
    },
    nested: {
      loading: "در حال دریافت اطلاعات...",
      loadError: "دریافت اطلاعات این بخش انجام نشد.",
      lookupError: "گزینه‌های این فرم در دسترس نیستند. دوباره تلاش کنید.",
      mutationError:
        "ذخیره تغییرات انجام نشد. ممکن است مجوز یا دسترسی لازم را نداشته باشید.",
      deleteError:
        "حذف مورد انتخاب‌شده انجام نشد. ممکن است مجوز یا دسترسی لازم را نداشته باشید.",
      forbiddenError: "مجوز یا دسترسی لازم برای انجام این عملیات را ندارید.",
      required: "تکمیل فیلدهای الزامی لازم است.",
      primary: "اصلی",
    },
    empty: {
      listTitle: "فردی مطابق فیلترها پیدا نشد",
      listDescription:
        "فیلترها را تغییر دهید یا در صورت داشتن مجوز، فرد جدیدی به CRM اضافه کنید.",
      contacts: "راه ارتباطی ثبت نشده است.",
      socials: "شبکه اجتماعی ثبت نشده است.",
      career: "سابقه شغلی ثبت نشده است.",
      education: "سابقه تحصیلی ثبت نشده است.",
    },
    errors: {
      listTitle: "دریافت فهرست افراد انجام نشد",
      listDescription:
        "در حال حاضر امکان دریافت فهرست افراد از سرور وجود ندارد. دوباره تلاش کنید.",
      detailTitle: "دریافت اطلاعات فرد انجام نشد",
      detailDescription:
        "پروفایل این فرد در حال حاضر قابل دریافت نیست. دوباره تلاش کنید.",
      permissionTitle: "دسترسی به فهرست افراد امکان‌پذیر نیست",
      permissionDescription:
        "برای مشاهده این بخش به مجوز فهرست افراد نیاز دارید.",
    },
    delete: {
      title: "حذف فرد",
      description:
        "آیا از حذف این فرد اطمینان دارید؟ این عملیات برای جلوگیری از حذف ناخواسته نیازمند تأیید نهایی است.",
    },
    notSpecified: "ثبت نشده",
  },

  profile: {
    title: "پروفایل کاربری",
    description: "اطلاعات حساب، هویت سازمانی و سطح دسترسی نشست فعلی",
    cards: {
      userName: "نام کاربر",
      organizationRole: "نقش سازمانی",
      permissionCount: "تعداد مجوزها",
      sessionStatus: "وضعیت نشست",
      sessionActive: "فعال",
    },
    account: {
      title: "اطلاعات حساب جاری",
      description: "اطلاعات احراز هویت و سطح دسترسی نشست فعلی",
      fields: {
        name: "نام",
        email: "ایمیل",
        role: "نقش",
        permissionCount: "تعداد مجوزها",
      },
    },
  },

  placeholders: {
    badge: "در حال توسعه",
    description:
      "پوسته این بخش آماده شده است. قابلیت‌های عملیاتی و اتصال به API در مراحل بعدی به این صفحه اضافه خواهد شد.",
  },

  date: {
    pickDate: "انتخاب تاریخ",
    pickDateTime: "انتخاب تاریخ و ساعت",
    pickDateRange: "انتخاب بازه تاریخ",
    rangeFrom: "از تاریخ",
    rangeTo: "تا تاریخ",
    rangeSeparator: "تا",
    timeLabel: "ساعت",
    timePlaceholder: "00:00",
    calendar: {
      previousMonth: "ماه قبل",
      nextMonth: "ماه بعد",
      selectMonth: "انتخاب ماه",
      selectYear: "انتخاب سال",
      today: "امروز",
      clear: "پاک کردن",
      weekdays: ["ش", "ی", "د", "س", "چ", "پ", "ج"],
      months: [
        "فروردین",
        "اردیبهشت",
        "خرداد",
        "تیر",
        "مرداد",
        "شهریور",
        "مهر",
        "آبان",
        "آذر",
        "دی",
        "بهمن",
        "اسفند",
      ],
    },
  },

  inputs: {
    currency: {
      defaultUnit: "ریال",
    },
  },

  errors: {
    route: {
      title: "خطایی در نمایش صفحه رخ داد",
      description:
        "بخشی از رابط کاربری با خطا مواجه شد. می‌توانید به داشبورد بازگردید و دوباره تلاش کنید.",
      backToDashboard: "بازگشت به داشبورد",
    },
  },
} as const






