import { useEffect } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { useQueryScope } from "@/lib/queryScope"
import { addCollaborationMember, archiveCollaborationChannel, archiveCollaborationTopic, createCollaborationChannel, createCollaborationTopic, getCollaborationChannel, getCollaborationMembers, removeCollaborationMember, sendPresenceHeartbeat, updateCollaborationChannel, updateCollaborationTopic } from "../api/collaboration.api"
import { getCollaborationTopics } from "../api/collaboration.api"
import type { CollaborationTopicCategory, CollaborationVisibility } from "../types/collaboration.types"

export const collaborationKeys = { all: ["collaboration"] as const, topics: ["collaboration", "topics"] as const, channel: (id: string) => ["collaboration", "channels", id] as const, members: (id: string) => ["collaboration", "channels", id, "members"] as const }
export function useCollaborationTopics(category?: CollaborationTopicCategory) { return useQuery({ queryKey: [...collaborationKeys.topics, category ?? "ALL", useQueryScope()], queryFn: () => getCollaborationTopics(category), refetchInterval: () => document.visibilityState === "visible" ? 25_000 : false }) }
export function useCollaborationChannel(id: string) { return useQuery({ queryKey: [...collaborationKeys.channel(id), useQueryScope()], queryFn: () => getCollaborationChannel(id), enabled: Boolean(id) }) }
export function useCollaborationMembers(id: string) { return useQuery({ queryKey: [...collaborationKeys.members(id), useQueryScope()], queryFn: () => getCollaborationMembers(id), enabled: Boolean(id), refetchInterval: () => document.visibilityState === "visible" ? 45_000 : false }) }
export function useCollaborationMutations() { const client = useQueryClient(); const refresh = () => client.invalidateQueries({ queryKey: collaborationKeys.all }); return { createTopic: useMutation({ mutationFn: createCollaborationTopic, onSuccess: refresh }), updateTopic: useMutation({ mutationFn: ({ id, ...payload }: { id: string; name?: string; description?: string; category?: CollaborationTopicCategory }) => updateCollaborationTopic(id, payload), onSuccess: refresh }), archiveTopic: useMutation({ mutationFn: archiveCollaborationTopic, onSuccess: refresh }), createChannel: useMutation({ mutationFn: ({ topicId, name, description, visibility }: { topicId: string; name: string; description?: string; visibility: CollaborationVisibility }) => createCollaborationChannel(topicId, { name, description, visibility }), onSuccess: refresh }), updateChannel: useMutation({ mutationFn: ({ id, ...payload }: { id: string; name?: string; description?: string; visibility?: CollaborationVisibility }) => updateCollaborationChannel(id, payload), onSuccess: refresh }), archiveChannel: useMutation({ mutationFn: archiveCollaborationChannel, onSuccess: refresh }), addMember: useMutation({ mutationFn: ({ channelId, userId }: { channelId: string; userId: string }) => addCollaborationMember(channelId, userId), onSuccess: refresh }), removeMember: useMutation({ mutationFn: ({ channelId, userId }: { channelId: string; userId: string }) => removeCollaborationMember(channelId, userId), onSuccess: refresh }) } }
export function usePresenceHeartbeat() { useEffect(() => { const beat = () => { if (document.visibilityState === "visible") void sendPresenceHeartbeat() }; beat(); const timer = window.setInterval(beat, 60_000); document.addEventListener("visibilitychange", beat); return () => { window.clearInterval(timer); document.removeEventListener("visibilitychange", beat) } }, []) }
