import { BriefcaseBusiness, Plus } from "lucide-react"
import { useState } from "react"

import { ConfirmDialog } from "@/components/shared/ConfirmDialog"
import { ErrorState } from "@/components/shared/ErrorState"
import { LoadingState } from "@/components/shared/LoadingState"
import { uiText } from "@/config/uiText"
import { getApiErrorMessage } from "@/lib/apiResponse"
import { Button } from "@workspace/ui/components/button"

import { useCreateEmploymentHistory, useCreateEmploymentPosition, useDeleteEmploymentHistory, useDeleteEmploymentPosition, usePersonEmploymentHistory, useUpdateEmploymentHistory, useUpdateEmploymentPosition } from "../hooks/usePeople"
import type { EmploymentHistory, EmploymentHistoryPayload, EmploymentPosition, EmploymentPositionPayload } from "../types/person.types"
import { formatPersonDate } from "../utils/personFormatters"
import { EmptyLine, RowActions, SectionHeader } from "./PersonContactsSection"
import { PersonEmploymentDialog } from "./PersonEmploymentDialog"
import { PersonPositionDialog } from "./PersonPositionDialog"

type PositionTarget = { employment: EmploymentHistory; position: EmploymentPosition | null }
export function PersonEmploymentSection({ personId, canEdit }: { personId: string; canEdit: boolean }) {
  const text = uiText.people; const query = usePersonEmploymentHistory(personId); const createEmployment = useCreateEmploymentHistory(personId); const updateEmployment = useUpdateEmploymentHistory(personId); const deleteEmployment = useDeleteEmploymentHistory(personId); const createPosition = useCreateEmploymentPosition(personId); const updatePosition = useUpdateEmploymentPosition(personId); const deletePosition = useDeleteEmploymentPosition(personId)
  const [editingEmployment, setEditingEmployment] = useState<EmploymentHistory | null | undefined>(undefined); const [editingPosition, setEditingPosition] = useState<PositionTarget | undefined>(); const [deletingEmployment, setDeletingEmployment] = useState<EmploymentHistory | null>(null); const [deletingPosition, setDeletingPosition] = useState<PositionTarget | undefined>()
  const items = Array.isArray(query.data) ? query.data : []
  async function saveEmployment(payload: EmploymentHistoryPayload) { if (editingEmployment) await updateEmployment.mutateAsync({ id: editingEmployment.id, payload }); else await createEmployment.mutateAsync(payload); setEditingEmployment(undefined) }
  async function savePosition(payload: EmploymentPositionPayload) { if (!editingPosition) return; if (editingPosition.position) await updatePosition.mutateAsync({ employmentId: editingPosition.employment.id, positionId: editingPosition.position.id, payload }); else await createPosition.mutateAsync({ employmentId: editingPosition.employment.id, payload }); setEditingPosition(undefined) }
  return <><SectionHeader title={text.sections.career} canEdit={canEdit} addLabel={text.career.addEmployment} onAdd={() => setEditingEmployment(null)} />{query.isLoading ? <LoadingState /> : query.isError ? <ErrorState title={text.nested.loadError} description={getApiErrorMessage(query.error, text.nested.loadError)} retryLabel={uiText.common.retry} onRetry={() => void query.refetch()} /> : items.length ? <div className="relative grid gap-4 before:absolute before:bottom-5 before:right-[11px] before:top-5 before:w-px before:bg-[var(--app-divider)]">{items.map((employment) => { const positions = Array.isArray(employment.positions) ? employment.positions : []; return <div key={employment.id} className="relative flex gap-4"><span className="relative z-10 mt-5 grid size-[23px] shrink-0 place-items-center rounded-full border-4 border-[var(--app-surface)] bg-[var(--app-primary)]"><BriefcaseBusiness className="size-2.5 text-white" /></span><div className="min-w-0 flex-1 rounded-[20px] border border-[var(--app-divider)] bg-[var(--app-background)]/45 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold">{employment.company?.brandName || employment.company?.legalName || text.notSpecified}</p>{employment.description ? <p className="mt-1 text-[10px] leading-5 text-[var(--app-text-secondary)]">{employment.description}</p> : null}</div>{canEdit ? <RowActions onEdit={() => setEditingEmployment(employment)} onDelete={() => setDeletingEmployment(employment)} /> : null}</div><div className="mt-3 grid gap-2">{positions.map((position) => <div key={position.id} className="flex items-start justify-between gap-3 rounded-xl border border-[var(--app-divider)] bg-[var(--app-surface)] p-3"><div><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-bold">{position.title}</p>{position.isCurrent ? <span className="rounded-full bg-[var(--app-primary-soft)] px-2 py-0.5 text-[8px] font-bold text-[var(--app-primary)]">{text.career.current}</span> : null}</div><p className="mt-1 text-[10px] text-[var(--app-text-secondary)]">{[formatPersonDate(position.startDate), formatPersonDate(position.endDate)].filter(Boolean).join(" — ")}</p>{position.description ? <p className="mt-1 text-[10px] leading-5 text-[var(--app-text-secondary)]">{position.description}</p> : null}</div>{canEdit ? <RowActions onEdit={() => setEditingPosition({ employment, position })} onDelete={() => setDeletingPosition({ employment, position })} /> : null}</div>)}{!positions.length ? <EmptyLine>{text.career.noPositions}</EmptyLine> : null}{canEdit ? <Button type="button" size="sm" variant="ghost" className="justify-self-start rounded-xl text-[var(--app-primary)]" onClick={() => setEditingPosition({ employment, position: null })}><Plus className="size-3.5" />{text.career.addPosition}</Button> : null}</div></div></div> })}</div> : <EmptyLine>{text.empty.career}</EmptyLine>}
  <PersonEmploymentDialog open={editingEmployment !== undefined} onOpenChange={(open) => { if (!open) setEditingEmployment(undefined) }} employment={editingEmployment} isPending={createEmployment.isPending || updateEmployment.isPending} error={createEmployment.error || updateEmployment.error} onSubmit={saveEmployment} />
  <PersonPositionDialog open={Boolean(editingPosition)} onOpenChange={(open) => { if (!open) setEditingPosition(undefined) }} position={editingPosition?.position} isPending={createPosition.isPending || updatePosition.isPending} error={createPosition.error || updatePosition.error} onSubmit={savePosition} />
  <ConfirmDialog open={Boolean(deletingEmployment)} onOpenChange={(open) => { if (!open) setDeletingEmployment(null) }} title={text.career.deleteEmploymentTitle} description={deleteEmployment.error ? getApiErrorMessage(deleteEmployment.error, text.nested.deleteError) : text.career.deleteEmploymentDescription} confirmLabel={text.actions.delete} isPending={deleteEmployment.isPending} onConfirm={async () => { if (deletingEmployment) { await deleteEmployment.mutateAsync(deletingEmployment.id); setDeletingEmployment(null) } }} />
  <ConfirmDialog open={Boolean(deletingPosition)} onOpenChange={(open) => { if (!open) setDeletingPosition(undefined) }} title={text.career.deletePositionTitle} description={deletePosition.error ? getApiErrorMessage(deletePosition.error, text.nested.deleteError) : text.career.deletePositionDescription} confirmLabel={text.actions.delete} isPending={deletePosition.isPending} onConfirm={async () => { if (deletingPosition?.position) { await deletePosition.mutateAsync({ employmentId: deletingPosition.employment.id, positionId: deletingPosition.position.id }); setDeletingPosition(undefined) } }} /></>
}
